using Advertise.Service.Managers.File;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.User
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    
    #line 2 "..\..\Views\User\Detail.cshtml"
    using Advertise.Core.Extensions;
    
    #line default
    #line hidden
    using Advertise.Core.Languages;
    
    #line 3 "..\..\Views\User\Detail.cshtml"
#line default
    #line hidden
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/User/Detail.cshtml")]
    public partial class Detail : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.User.UserDetailViewModel>
    {
        public Detail()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\User\Detail.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Public._PublicLayout;
    ViewBag.Title = Admin.ProfilePage.PlusWord(" ").PlusWord(Admin.User).PlusWord(" ").PlusWord(Model.FullName);

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"section-wrap\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"section overflowable\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"sidebar left user-profile meta-detail\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"sidebar-item author-bio\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\User\Detail.cshtml"
                
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\User\Detail.cshtml"
                 if (Model.AvatarFileName != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"product-detail company-logo\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 708), Tuple.Create("\"", 769)
            
            #line 16 "..\..\Views\User\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 714), Tuple.Create<System.Object, System.Int32>(FileConst.ImagesWebPath.PlusWord(Model.AvatarFileName)
            
            #line default
            #line hidden
, 714), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 770), Tuple.Create("\"", 815)
, Tuple.Create(Tuple.Create("", 776), Tuple.Create("User", 776), true)
, Tuple.Create(Tuple.Create(" ", 780), Tuple.Create("Avatar", 781), true)
, Tuple.Create(Tuple.Create(" ", 787), Tuple.Create("Image", 788), true)
            
            #line 16 "..\..\Views\User\Detail.cshtml"
                                  , Tuple.Create(Tuple.Create(" ", 793), Tuple.Create<System.Object, System.Int32>(Model.AvatarFileName
            
            #line default
            #line hidden
, 794), false)
);

WriteLiteral(">\r\n                    </div>\r\n");

            
            #line 18 "..\..\Views\User\Detail.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"product-detail company-logo\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 998), Tuple.Create("\"", 1026)
            
            #line 22 "..\..\Views\User\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 1004), Tuple.Create<System.Object, System.Int32>(FileConst.NoAvatarPth
            
            #line default
            #line hidden
, 1004), false)
);

WriteLiteral(" alt=\"user without avatar image\"");

WriteLiteral(">\r\n                    </div>\r\n");

            
            #line 24 "..\..\Views\User\Detail.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" data-on-load=\"ajaxGetUserInformations\"");

WriteLiteral("  data-param=\"");

            
            #line 25 "..\..\Views\User\Detail.cshtml"
                                                                    Write(Model.UserName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>\r\n                <p");

WriteLiteral(" class=\"text-header\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\User\Detail.cshtml"
                                  Write(Model.FullName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <p");

WriteLiteral(" class=\"text-oneline first-load-info\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-envelope fa-spin fa-fw fa-2x\"");

WriteLiteral("></i>\r\n                </p>\r\n                <h6>\r\n                    <br>\r\n    " +
"            </h6>\r\n");

            
            #line 33 "..\..\Views\User\Detail.cshtml"
                
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\User\Detail.cshtml"
                 if (Model.CompanyTitle != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p");

WriteLiteral(" class=\"text-oneline\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\User\Detail.cshtml"
                   Write(Admin.Company.PlusWord(": "));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1686), Tuple.Create("\"", 1791)
            
            #line 37 "..\..\Views\User\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 1693), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Company.Detail(Model.CompanyAlias,Model.CompanyTitle)).AddSlug(Model.CompanyTitle)
            
            #line default
            #line hidden
, 1693), false)
);

WriteLiteral(" class=\"user-meta-company-title\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"primary\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\User\Detail.cshtml"
                                                      Write(Model.CompanyTitle);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </a>\r\n                    </p>\r\n");

            
            #line 41 "..\..\Views\User\Detail.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div");

WriteLiteral(" class=\"sidebar-item product-info\"");

WriteLiteral(">\r\n                <h4>");

            
            #line 44 "..\..\Views\User\Detail.cshtml"
               Write(Admin.ContactInfo.PlusWord(": "));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                <hr");

WriteLiteral(" class=\"line-separator\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"information-layout\"");

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Views\User\Detail.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\User\Detail.cshtml"
                     if (Model.HomeNumber != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"information-layout-item\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"text-header\"");

WriteLiteral(">");

            
            #line 50 "..\..\Views\User\Detail.cshtml"
                                              Write(Admin.Phone.PlusWord(": "));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p");

WriteLiteral(" id=\"HomeeNumber\"");

WriteLiteral(" class=\"company-detail side-text first-load-info\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-phone fa-spin fa-fw fa-2x\"");

WriteLiteral("></i>\r\n                            </p>\r\n                        </div>\r\n");

            
            #line 55 "..\..\Views\User\Detail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 56 "..\..\Views\User\Detail.cshtml"
                     if (Model.PhoneNumber != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"information-layout-item\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"text-header\"");

WriteLiteral(">");

            
            #line 59 "..\..\Views\User\Detail.cshtml"
                                              Write(Admin.Mobile.PlusWord(": "));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p");

WriteLiteral(" id=\"PhoneNumber\"");

WriteLiteral(" class=\"company-detail side-text first-load-info\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-mobile fa-spin fa-fw fa-2x\"");

WriteLiteral("></i>\r\n                            </p>\r\n                        </div>\r\n");

            
            #line 64 "..\..\Views\User\Detail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 65 "..\..\Views\User\Detail.cshtml"
                     if (Model.Email != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"information-layout-item\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"text-header\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\User\Detail.cshtml"
                                              Write(Admin.Email.PlusWord(": "));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p");

WriteLiteral(" id=\"EmailAddress\"");

WriteLiteral(" class=\"company-detail side-text first-load-info\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-envelope fa-spin fa-fw fa-2x\"");

WriteLiteral("></i>\r\n                            </p>\r\n                        </div>\r\n");

            
            #line 73 "..\..\Views\User\Detail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 74 "..\..\Views\User\Detail.cshtml"
                     if (Model.Address != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"information-layout-item\"");

WriteLiteral(">\r\n                            <p");

WriteLiteral(" class=\"text-header\"");

WriteLiteral(">");

            
            #line 77 "..\..\Views\User\Detail.cshtml"
                                              Write(Admin.Address.PlusWord(": "));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                            <p");

WriteLiteral(" id=\"AddressPlace\"");

WriteLiteral(" class=\"company-detail side-address side-text first-load-info\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-map-signs fa-spin fa-fw fa-2x\"");

WriteLiteral("></i>\r\n                            </p>\r\n                        </div>\r\n");

            
            #line 82 "..\..\Views\User\Detail.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"content right meta-detail-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"headline simple primary\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" name=\"gallery-section\"");

WriteLiteral("></a>\r\n                <h4>\r\n                    <i");

WriteLiteral(" class=\"fa fa-image\"");

WriteLiteral("></i> \r\n                    <span>");

            
            #line 91 "..\..\Views\User\Detail.cshtml"
                     Write(Admin.Galery);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"comment-list company-images\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"company-images-wrapper\"");

WriteLiteral("></div>\r\n            </div>\r\n            <br>\r\n            <br>\r\n        </div>\r\n" +
"        <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
