#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.CompanyConversation
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CompanyConversation/_Create.cshtml")]
    public partial class _Create : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public _Create()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"comment-wrap comment-reply\"");

WriteLiteral(">\r\n    <textarea");

WriteLiteral(" id=\"commentBody\"");

WriteLiteral(" name=\"commentBody\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 143), Tuple.Create("\"", 183)
            
            #line 3 "..\..\Views\CompanyConversation\_Create.cshtml"
, Tuple.Create(Tuple.Create("", 157), Tuple.Create<System.Object, System.Int32>(Admin.PrivateConversation
            
            #line default
            #line hidden
, 157), false)
);

WriteLiteral(" class=\"tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 204), Tuple.Create("\"", 238)
            
            #line 3 "..\..\Views\CompanyConversation\_Create.cshtml"
                                       , Tuple.Create(Tuple.Create("", 212), Tuple.Create<System.Object, System.Int32>(Admin.PrivateConversation
            
            #line default
            #line hidden
, 212), false)
);

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"");

            
            #line 3 "..\..\Views\CompanyConversation\_Create.cshtml"
                                                                                                                                                                                Write(Admin.RequiredExplain);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></textarea>\r\n    <span");

WriteLiteral(" class=\"field-validation-error\"");

WriteLiteral(" data-valmsg-for=\"commentBody\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n    <button");

WriteLiteral(" id=\"btnSendConversation\"");

WriteLiteral(" class=\"button primary\"");

WriteLiteral(" data-on-click=\"ajaxSendCompanyConversation\"");

WriteLiteral(" >");

            
            #line 5 "..\..\Views\CompanyConversation\_Create.cshtml"
                                                                                                    Write(Admin.Send);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
