#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.SeoUrl
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    
    #line 2 "..\..\Views\SeoUrl\_Item.cshtml"
    using Advertise.Service.Managers.File;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\SeoUrl\_Item.cshtml"
    using Advertise.Service.Services.Permissions;
    
    #line default
    #line hidden
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SeoUrl/_Item.cshtml")]
    public partial class _Item : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.SeoUrl.SeoUrlViewModel>
    {
        public _Item()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"landing-items nov-item-height-030\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"product-item column landing-column\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"nov-item-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"action-section without-share\"");

WriteLiteral(">\r\n");

            
            #line 9 "..\..\Views\SeoUrl\_Item.cshtml"
                
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\SeoUrl\_Item.cshtml"
                 if (User.IsInRole(PermissionConst.CanSeoUrlEdit) || User.IsInRole(PermissionConst.CanSeoUrlDeleteAjax))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"item-edit-wrapper\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-pencil-square\"");

WriteLiteral("></i>\r\n                        <ul");

WriteLiteral(" class=\"item-edit-list\"");

WriteLiteral(">\r\n");

            
            #line 14 "..\..\Views\SeoUrl\_Item.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\SeoUrl\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanSeoUrlEdit))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 885), Tuple.Create("\"", 930)
            
            #line 17 "..\..\Views\SeoUrl\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 892), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.SeoUrl.Edit(Model.Id))
            
            #line default
            #line hidden
, 892), false)
);

WriteLiteral(">\r\n                                        <span>");

            
            #line 18 "..\..\Views\SeoUrl\_Item.cshtml"
                                         Write(Admin.Edit);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-pencil fa-flip-horizontal\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 22 "..\..\Views\SeoUrl\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 23 "..\..\Views\SeoUrl\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanSeoUrlDeleteAjax))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" data-on-click=\"removeConfirm\"");

WriteLiteral(" data-param=\"");

            
            #line 26 "..\..\Views\SeoUrl\_Item.cshtml"
                                                                                                      Write(Url.Action(MVC.SeoUrl.DeleteAjax(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                        <span>");

            
            #line 27 "..\..\Views\SeoUrl\_Item.cshtml"
                                         Write(Admin.Delete);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-trash\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 31 "..\..\Views\SeoUrl\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n");

            
            #line 34 "..\..\Views\SeoUrl\_Item.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div");

WriteLiteral(" class=\"rectangle-section\"");

WriteLiteral(">\r\n                <span>\r\n");

WriteLiteral("                    ");

            
            #line 38 "..\..\Views\SeoUrl\_Item.cshtml"
               Write(Admin.Code);

            
            #line default
            #line hidden
WriteLiteral(" :\r\n                    <span> ");

            
            #line 39 "..\..\Views\SeoUrl\_Item.cshtml"
                      Write(Model.Redirection.ToInt32());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </span>\r\n            </div>\r\n        </div>\r\n        <di" +
"v");

WriteLiteral(" class=\"nov-item-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"image-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"product-preview-actions\"");

WriteLiteral(">\r\n                    <figure");

WriteLiteral(" class=\"product-preview-image\"");

WriteLiteral(">\r\n                        <a>\r\n                            <div");

WriteLiteral(" class=\"item-preview-image\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2407), Tuple.Create("\"", 2432)
            
            #line 49 "..\..\Views\SeoUrl\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 2413), Tuple.Create<System.Object, System.Int32>(FileConst.Redirect
            
            #line default
            #line hidden
, 2413), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 2433), Tuple.Create("\"", 2457)
            
            #line 49 "..\..\Views\SeoUrl\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 2439), Tuple.Create<System.Object, System.Int32>(Admin.Redirection
            
            #line default
            #line hidden
, 2439), false)
);

WriteLiteral(">\r\n                            </div>\r\n                        </a>\r\n            " +
"        </figure>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"caption-section\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"novinak-title-link\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"novinak-title text-header\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\SeoUrl\_Item.cshtml"
                                                    Write(Model.Redirection);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"info-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"top-part\"");

WriteLiteral(">\r\n                    <a>\r\n                        <p>");

            
            #line 63 "..\..\Views\SeoUrl\_Item.cshtml"
                            if (Model.IsActive){
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\SeoUrl\_Item.cshtml"
                                                 Write(Admin.Active);

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\SeoUrl\_Item.cshtml"
                                                                          }else{
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\SeoUrl\_Item.cshtml"
                                                                                 Write(Admin.Inactive);

            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\SeoUrl\_Item.cshtml"
                                                                                                            }
            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"middle-part\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"small-state ltr-text\"");

WriteLiteral(">");

            
            #line 67 "..\..\Views\SeoUrl\_Item.cshtml"
                                               Write(Model.AbsoulateUrl);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"bottom-part\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"small-state ltr-text\"");

WriteLiteral(">");

            
            #line 70 "..\..\Views\SeoUrl\_Item.cshtml"
                                               Write(Model.CurrentUrl);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"clearboth\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
