using Advertise.Service.Managers.File;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    
    #line 1 "..\..\Views\Newsletter\_AddItem.cshtml"
#line default
    #line hidden
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Newsletter/_AddItem.cshtml")]
    public partial class _Views_Newsletter__AddItem_cshtml : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public _Views_Newsletter__AddItem_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"landing-items newsletter-items\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"product-item column landing-column\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"product-preview-actions\"");

WriteLiteral(">\r\n            <figure");

WriteLiteral(" class=\"product-preview-image\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 257), Tuple.Create("\"", 300)
            
            #line 6 "..\..\Views\Newsletter\_AddItem.cshtml"
, Tuple.Create(Tuple.Create("", 264), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Newsletter.Create())
            
            #line default
            #line hidden
, 264), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"item-preview-image\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 386), Tuple.Create("\"", 410)
            
            #line 8 "..\..\Views\Newsletter\_AddItem.cshtml"
, Tuple.Create(Tuple.Create("", 392), Tuple.Create<System.Object, System.Int32>(FileConst.NewItem
            
            #line default
            #line hidden
, 392), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 411), Tuple.Create("\"", 437)
            
            #line 8 "..\..\Views\Newsletter\_AddItem.cshtml"
, Tuple.Create(Tuple.Create("", 417), Tuple.Create<System.Object, System.Int32>(Admin.AddNewsletter
            
            #line default
            #line hidden
, 417), false)
);

WriteLiteral(">\r\n                    </div>\r\n                </a>\r\n            </figure>\r\n     " +
"   </div>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 540), Tuple.Create("\"", 583)
            
            #line 13 "..\..\Views\Newsletter\_AddItem.cshtml"
, Tuple.Create(Tuple.Create("", 547), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Newsletter.Create())
            
            #line default
            #line hidden
, 547), false)
);

WriteLiteral(" class=\"item-part-two-link\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"part-two new-item-add\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-plus-square\"");

WriteLiteral("></i>\r\n                <span>");

            
            #line 16 "..\..\Views\Newsletter\_AddItem.cshtml"
                 Write(Admin.AddNewsletter);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </p>\r\n        </a>\r\n        <div");

WriteLiteral(" class=\"clearboth\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
