#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Shared.FineUploaderTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/FineUploaderTemplates/_FineUploaderTemplate.cshtml")]
    public partial class _FineUploaderTemplate : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public _FineUploaderTemplate()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/template\"");

WriteLiteral(" id=\"qq-template-gallery\"");

WriteLiteral(">\r\n    <div class=\"qq-uploader-selector qq-uploader qq-gallery\" qq-drop-area-text" +
"=\"فایل ها را اینجا بکشید\">\r\n        <div class=\"qq-total-progress-bar-container-" +
"selector qq-total-progress-bar-container\">\r\n            <div role=\"progressbar\" " +
"aria-valuenow=\"0\" aria-valuemin=\"0\" aria-valuemax=\"100\" class=\"qq-total-progress" +
"-bar-selector qq-progress-bar qq-total-progress-bar\"></div>\r\n        </div>\r\n   " +
"     <div class=\"qq-upload-drop-area-selector qq-upload-drop-area\" qq-hide-dropz" +
"one>\r\n            <span class=\"qq-upload-drop-area-text-selector\"></span>\r\n     " +
"   </div>\r\n        <div class=\"qq-upload-button-selector qq-upload-button\">\r\n   " +
"         <div>آپلود فایل</div>\r\n        </div>\r\n        <span class=\"qq-drop-pro" +
"cessing-selector qq-drop-processing\">\r\n            <span>Processing dropped file" +
"s...</span>\r\n            <span class=\"qq-drop-processing-spinner-selector qq-dro" +
"p-processing-spinner\"></span>\r\n        </span>\r\n        <ul class=\"qq-upload-lis" +
"t-selector qq-upload-list\" role=\"region\" aria-live=\"polite\" aria-relevant=\"addit" +
"ions removals\">\r\n            <li>\r\n                <span role=\"status\" class=\"qq" +
"-upload-status-text-selector qq-upload-status-text\"></span>\r\n                <di" +
"v class=\"qq-progress-bar-container-selector qq-progress-bar-container\">\r\n       " +
"             <div role=\"progressbar\" aria-valuenow=\"0\" aria-valuemin=\"0\" aria-va" +
"luemax=\"100\" class=\"qq-progress-bar-selector qq-progress-bar\"></div>\r\n          " +
"      </div>\r\n                <span class=\"qq-upload-spinner-selector qq-upload-" +
"spinner\"></span>\r\n                <div class=\"qq-thumbnail-wrapper\">\r\n          " +
"          <img class=\"qq-thumbnail-selector\" qq-max-size=\"120\" qq-server-scale>\r" +
"\n                </div>\r\n                <button type=\"button\" class=\"qq-upload-" +
"cancel-selector qq-upload-cancel\">X</button>\r\n                <button type=\"butt" +
"on\" class=\"qq-upload-retry-selector qq-upload-retry\">\r\n                    <span" +
" class=\"qq-btn qq-retry-icon\" aria-label=\"Retry\"></span>\r\n                    Re" +
"try\r\n                </button>\r\n\r\n                <div class=\"qq-file-info\">\r\n  " +
"                  <div class=\"qq-file-name\">\r\n                        <span clas" +
"s=\"qq-upload-file-selector qq-upload-file\"></span>\r\n                        <spa" +
"n class=\"qq-edit-filename-icon-selector qq-edit-filename-icon\" aria-label=\"Edit " +
"filename\"></span>\r\n                    </div>\r\n                    <input class=" +
"\"qq-edit-filename-selector qq-edit-filename\" tabindex=\"0\" type=\"text\">\r\n        " +
"            <span class=\"qq-upload-size-selector qq-upload-size\"></span>\r\n      " +
"              <button type=\"button\" class=\"qq-btn qq-upload-delete-selector qq-u" +
"pload-delete\">\r\n                        <span class=\"qq-btn qq-delete-icon\" aria" +
"-label=\"Delete\"></span>\r\n                    </button>\r\n                    <but" +
"ton type=\"button\" class=\"qq-btn qq-upload-pause-selector qq-upload-pause\">\r\n    " +
"                    <span class=\"qq-btn qq-pause-icon\" aria-label=\"Pause\"></span" +
">\r\n                    </button>\r\n                    <button type=\"button\" clas" +
"s=\"qq-btn qq-upload-continue-selector qq-upload-continue\">\r\n                    " +
"    <span class=\"qq-btn qq-continue-icon\" aria-label=\"Continue\"></span>\r\n       " +
"             </button>\r\n                </div>\r\n            </li>\r\n        </ul>" +
"\r\n\r\n        <dialog class=\"qq-alert-dialog-selector\">\r\n            <div class=\"q" +
"q-dialog-message-selector\"></div>\r\n            <div class=\"qq-dialog-buttons\">\r\n" +
"                <button type=\"button\" class=\"qq-cancel-button-selector\">Close</b" +
"utton>\r\n            </div>\r\n        </dialog>\r\n\r\n        <dialog class=\"qq-confi" +
"rm-dialog-selector\">\r\n            <div class=\"qq-dialog-message-selector\"></div>" +
"\r\n            <div class=\"qq-dialog-buttons\">\r\n                <button type=\"but" +
"ton\" class=\"qq-cancel-button-selector\">No</button>\r\n                <button type" +
"=\"button\" class=\"qq-ok-button-selector\">Yes</button>\r\n            </div>\r\n      " +
"  </dialog>\r\n\r\n        <dialog class=\"qq-prompt-dialog-selector\">\r\n            <" +
"div class=\"qq-dialog-message-selector\"></div>\r\n            <input type=\"text\">\r\n" +
"            <div class=\"qq-dialog-buttons\">\r\n                <button type=\"butto" +
"n\" class=\"qq-cancel-button-selector\">Cancel</button>\r\n                <button ty" +
"pe=\"button\" class=\"qq-ok-button-selector\">Ok</button>\r\n            </div>\r\n     " +
"   </dialog>\r\n    </div>\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
