#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ForgotPasswordConfirm.cshtml")]
    public partial class ForgotPasswordConfirm : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.Account.ForgotPasswordViewModel>
    {
        public ForgotPasswordConfirm()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Public._PublicLayout;
    ViewBag.Title = Admin.PasswordForgotten;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"register-wrapper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-box-item form-popup register-structure\"");

WriteLiteral(">\r\n        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 339), Tuple.Create("\"", 401)
            
            #line 9 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
, Tuple.Create(Tuple.Create("", 348), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.ConfirmationForgotPassword())
            
            #line default
            #line hidden
, 348), false)
);

WriteLiteral(" method=\"Post\"");

WriteLiteral(" data-on-load=\"validateForgotPassword\"");

WriteLiteral(" class=\"form-popup-content\"");

WriteLiteral(">\r\n            <h4");

WriteLiteral(" class=\"popup-title register-header\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-question-circle-o\"");

WriteLiteral("></i>\r\n                <span>");

            
            #line 12 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
                 Write(Admin.ForgetPassWord);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </h4>\r\n            <hr");

WriteLiteral(" class=\"line-separator short register-hr\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            <p");

WriteLiteral(" class=\"spaced register-paragraph\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-exclamation-circle\"");

WriteLiteral("></i>\r\n                <span>");

            
            #line 20 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
                 Write(Admin.MessageEnterEmailForgetPassword);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </p>\r\n            \r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-envelope register-icon\"");

WriteLiteral("></i>\r\n                <label");

WriteLiteral(" for=\"Email\"");

WriteLiteral(" class=\"rl-label register-label\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
                                                              Write(Admin.Email);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Email\"");

WriteLiteral(" name=\"Email\"");

WriteLiteral(" class=\"register-input\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1289), Tuple.Create("\"", 1322)
            
            #line 26 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
               , Tuple.Create(Tuple.Create("", 1303), Tuple.Create<System.Object, System.Int32>(Admin.ExampleEmail
            
            #line default
            #line hidden
, 1303), false)
);

WriteLiteral("/>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button mid dark register-top-btn\"");

WriteLiteral(">\r\n                    <span>");

            
            #line 31 "..\..\Views\Account\ForgotPasswordConfirm.cshtml"
                     Write(Admin.SendingPassword);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </button>\r\n            </div>\r\n            \r\n           " +
" <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral("></div>\r\n        </form>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
