#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Login.cshtml")]
    public partial class Login : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.Account.LoginViewModel>
    {
        public Login()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Account\Login.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Public._PublicLayout;
    ViewBag.Title = Admin.Login;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"register-wrapper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-box-item form-popup register-structure\"");

WriteLiteral(">\r\n        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 318), Tuple.Create("\"", 359)
            
            #line 9 "..\..\Views\Account\Login.cshtml"
, Tuple.Create(Tuple.Create("", 327), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.Login())
            
            #line default
            #line hidden
, 327), false)
);

WriteLiteral(" method=\"Post\"");

WriteLiteral(" class=\"form-popup-content\"");

WriteLiteral(" data-on-load=\"validateLogin\"");

WriteLiteral(">\r\n            <h4");

WriteLiteral(" class=\"register-header popup-title\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-sign-in\"");

WriteLiteral("></i>\r\n                <span>");

            
            #line 12 "..\..\Views\Account\Login.cshtml"
                 Write(Admin.Login);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </h4>\r\n            <hr");

WriteLiteral(" class=\"line-separator register-hr\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Account\Login.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Account\Login.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"returnUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 775), Tuple.Create("\"", 801)
            
            #line 17 "..\..\Views\Account\Login.cshtml"
, Tuple.Create(Tuple.Create("", 783), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnUrl
            
            #line default
            #line hidden
, 783), false)
);

WriteLiteral(" />\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-user register-icon\"");

WriteLiteral("></i>\r\n                <label");

WriteLiteral(" for=\"UserName\"");

WriteLiteral(" class=\"rl-label register-label\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Account\Login.cshtml"
                                                                 Write(Admin.MobileOrEmailOrUsername);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"UserName\"");

WriteLiteral(" name=\"UserName\"");

WriteLiteral(" class=\"register-input\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1107), Tuple.Create("\"", 1151)
            
            #line 22 "..\..\Views\Account\Login.cshtml"
                     , Tuple.Create(Tuple.Create("", 1121), Tuple.Create<System.Object, System.Int32>(Admin.MobileOrEmailOrUsername
            
            #line default
            #line hidden
, 1121), false)
);

WriteLiteral(">\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-lock register-icon\"");

WriteLiteral("></i>\r\n                <label");

WriteLiteral(" for=\"Password\"");

WriteLiteral(" class=\"rl-label register-label\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Account\Login.cshtml"
                                                                 Write(Admin.PassWord);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"Password\"");

WriteLiteral(" name=\"Password\"");

WriteLiteral(" class=\"register-input\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1464), Tuple.Create("\"", 1493)
            
            #line 28 "..\..\Views\Account\Login.cshtml"
                         , Tuple.Create(Tuple.Create("", 1478), Tuple.Create<System.Object, System.Int32>(Admin.PassWord
            
            #line default
            #line hidden
, 1478), false)
);

WriteLiteral(">\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"RememberMe\"");

WriteLiteral(" name=\"RememberMe\"");

WriteLiteral(" class=\"hide-none-imp\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" checked>\r\n                <label");

WriteLiteral(" for=\"RememberMe\"");

WriteLiteral(" class=\"label-check register-label\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"checkbox primary primary\"");

WriteLiteral(">\r\n                        <span></span>\r\n                    </span>\r\n          " +
"          <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" class=\"primary register-check-text\"");

WriteLiteral(">");

            
            #line 37 "..\..\Views\Account\Login.cshtml"
                                                                                Write(Admin.RememberMe);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </label>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"register-bottom-click\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 43 "..\..\Views\Account\Login.cshtml"
               Write(Admin.ForgetPassWord);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2201), Tuple.Create("\"", 2256)
            
            #line 44 "..\..\Views\Account\Login.cshtml"
, Tuple.Create(Tuple.Create("", 2208), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.ForgotPasswordConfirm())
            
            #line default
            #line hidden
, 2208), false)
);

WriteLiteral(" class=\"primary register-link\"");

WriteLiteral(">");

            
            #line 44 "..\..\Views\Account\Login.cshtml"
                                                                                                        Write(Admin.ClickHere);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </p>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button mid dark register-top-btn\"");

WriteLiteral(">\r\n                    <span>");

            
            #line 50 "..\..\Views\Account\Login.cshtml"
                     Write(Admin.Login);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </button>\r\n            </div>\r\n\r\n            <hr");

WriteLiteral(" class=\"line-separator double register-hr\"");

WriteLiteral(">\r\n            \r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2709), Tuple.Create("\"", 2769)
            
            #line 57 "..\..\Views\Account\Login.cshtml"
, Tuple.Create(Tuple.Create("", 2716), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.ExternalLogin("Google", "/"))
            
            #line default
            #line hidden
, 2716), false)
);

WriteLiteral(" class=\"button mid twt google-color\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Account\Login.cshtml"
                                                                                                                               Write(Admin.LoginGoogle);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral("></div>\r\n        </form>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
