#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ResetPasswordConfirm.cshtml")]
    public partial class ResetPasswordConfirm : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.Account.ResetPasswordViewModel>
    {
        public ResetPasswordConfirm()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Public._PublicLayout;
    ViewBag.Title = Admin.ResetPassword;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"register-wrapper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-box-item form-popup register-structure\"");

WriteLiteral(">\r\n        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 334), Tuple.Create("\"", 395)
            
            #line 9 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
, Tuple.Create(Tuple.Create("", 343), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.ConfirmationResetPassword())
            
            #line default
            #line hidden
, 343), false)
);

WriteLiteral(" method=\"Post\"");

WriteLiteral(" data-on-load=\"validateConfirmationResetPassword\"");

WriteLiteral(" class=\"form-popup-content\"");

WriteLiteral(">\r\n            <h4");

WriteLiteral(" class=\"popup-title register-header\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-unlock-alt\"");

WriteLiteral("></i>\r\n                <span>");

            
            #line 12 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                 Write(Admin.ResetPassword);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </h4>\r\n            <hr");

WriteLiteral(" class=\"line-separator register-hr\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 16 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"Code\"");

WriteLiteral(" name=\"Code\"");

WriteAttribute("value", Tuple.Create(" value=\"", 847), Tuple.Create("\"", 866)
            
            #line 17 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
, Tuple.Create(Tuple.Create("", 855), Tuple.Create<System.Object, System.Int32>(Model.Code
            
            #line default
            #line hidden
, 855), false)
);

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UserId\"");

WriteLiteral(" name=\"UserId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 930), Tuple.Create("\"", 951)
            
            #line 18 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
, Tuple.Create(Tuple.Create("", 938), Tuple.Create<System.Object, System.Int32>(Model.UserId
            
            #line default
            #line hidden
, 938), false)
);

WriteLiteral(" />\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-envelope register-icon\"");

WriteLiteral("></i>\r\n                <label");

WriteLiteral(" for=\"Email\"");

WriteLiteral(" class=\"rl-label register-label\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                              Write(Admin.Email);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Email\"");

WriteLiteral(" name=\"Email\"");

WriteLiteral(" class=\"register-input\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1234), Tuple.Create("\"", 1267)
            
            #line 23 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
               , Tuple.Create(Tuple.Create("", 1248), Tuple.Create<System.Object, System.Int32>(Admin.ExampleEmail
            
            #line default
            #line hidden
, 1248), false)
);

WriteLiteral(" />\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-asterisk register-icon\"");

WriteLiteral("></i>\r\n                <label");

WriteLiteral(" for=\"Password\"");

WriteLiteral(" class=\"rl-label register-label\"");

WriteLiteral(">");

            
            #line 28 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                                 Write(Admin.PassWord);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <input");

WriteLiteral(" type=\"Password\"");

WriteLiteral(" id=\"Password\"");

WriteLiteral(" name=\"Password\"");

WriteLiteral(" class=\"register-input\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1586), Tuple.Create("\"", 1615)
            
            #line 29 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                         , Tuple.Create(Tuple.Create("", 1600), Tuple.Create<System.Object, System.Int32>(Admin.PassWord
            
            #line default
            #line hidden
, 1600), false)
);

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"");

            
            #line 29 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                                                                                                                        Write(Admin.RequiredPassword);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-va-equalto-other=\"Password\"");

WriteLiteral(" data-val-length=\"");

            
            #line 29 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                                                                                                                                                                                                   Write(Admin.MessageLengthPassword);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-val-length-min=\"6\"");

WriteLiteral(" data-val-length-max=\"100\"");

WriteLiteral(" />\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-asterisk register-icon\"");

WriteLiteral("></i>\r\n                <label");

WriteLiteral(" for=\"ConfirmPassword\"");

WriteLiteral(" class=\"rl-label register-label\"");

WriteLiteral(">");

            
            #line 34 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                                        Write(Admin.ConfirmPassword);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"ConfirmPassword\"");

WriteLiteral(" class=\"register-input\"");

WriteLiteral(" name=\"ConfirmPassword\"");

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 2152), Tuple.Create("\"", 2188)
            
            #line 35 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                       , Tuple.Create(Tuple.Create("", 2166), Tuple.Create<System.Object, System.Int32>(Admin.ConfirmPassword
            
            #line default
            #line hidden
, 2166), false)
);

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"");

            
            #line 35 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                                                                                                                                             Write(Admin.RequiredConfirmPassword);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-val-length=\"");

            
            #line 35 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                                                                                                                                                                                              Write(Admin.MessageLengthPassword);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-val-length-min=\"6\"");

WriteLiteral(" data-val-length-max=\"100\"");

WriteLiteral(" data-val-equal-to=\"");

            
            #line 35 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                                                                                                                                                                                                                                                                                                                                 Write(Admin.WarningEqualPasswords);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-val-equalto-other=\"Password\"");

WriteLiteral(" />\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"button mid dark register-top-btn\"");

WriteLiteral(">\r\n                    <span>");

            
            #line 40 "..\..\Views\Account\ResetPasswordConfirm.cshtml"
                     Write(Admin.ResetPassword);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </button>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral("></div>\r\n        </form>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
