#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.AdsOption
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    
    #line 2 "..\..\Views\AdsOption\_Item.cshtml"
    using Advertise.Core.Extensions;
    
    #line default
    #line hidden
    using Advertise.Core.Languages;
    
    #line 3 "..\..\Views\AdsOption\_Item.cshtml"
    using Advertise.Core.Types;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\AdsOption\_Item.cshtml"
    using Advertise.Service.Managers.File;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\AdsOption\_Item.cshtml"
    using Advertise.Service.Services.Permissions;
    
    #line default
    #line hidden
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AdsOption/_Item.cshtml")]
    public partial class _Item : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.AdsOption.AdsOptionViewModel>
    {
        public _Item()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"landing-items nov-item-height-030\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"product-item column landing-column\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"nov-item-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"action-section without-share\"");

WriteLiteral(">\r\n");

            
            #line 11 "..\..\Views\AdsOption\_Item.cshtml"
                
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\AdsOption\_Item.cshtml"
                 if (User.IsInRole(PermissionConst.CanAdsOptionEdit))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"item-edit-wrapper\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-pencil-square\"");

WriteLiteral("></i>\r\n                        <ul");

WriteLiteral(" class=\"item-edit-list\"");

WriteLiteral(">\r\n");

            
            #line 16 "..\..\Views\AdsOption\_Item.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\AdsOption\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanAdsOptionEdit))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 906), Tuple.Create("\"", 954)
            
            #line 19 "..\..\Views\AdsOption\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 913), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.AdsOption.Edit(Model.Id))
            
            #line default
            #line hidden
, 913), false)
);

WriteLiteral(">\r\n                                        <span>");

            
            #line 20 "..\..\Views\AdsOption\_Item.cshtml"
                                         Write(Admin.Edit);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-pencil fa-flip-horizontal\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 24 "..\..\Views\AdsOption\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n");

            
            #line 27 "..\..\Views\AdsOption\_Item.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            <div");

WriteLiteral(" class=\"rectangle-section\"");

WriteLiteral(">\r\n                <span>");

            
            #line 30 "..\..\Views\AdsOption\_Item.cshtml"
                 Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"nov-item-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"image-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"product-preview-actions\"");

WriteLiteral(">\r\n                    <figure");

WriteLiteral(" class=\"product-preview-image\"");

WriteLiteral(">\r\n                        <a>\r\n                            <div");

WriteLiteral(" class=\"item-preview-image\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1767), Tuple.Create("\"", 1846)
            
            #line 39 "..\..\Views\AdsOption\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 1773), Tuple.Create<System.Object, System.Int32>(Model.Type == AdsType.Banner ? FileConst.BannerItem : FileConst.Slider
            
            #line default
            #line hidden
, 1773), false)
);

WriteLiteral(" alt=\"ads option\"");

WriteLiteral(">\r\n                            </div>\r\n                        </a>\r\n            " +
"        </figure>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"caption-section\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"novinak-title-link\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"novinak-title text-header\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\AdsOption\_Item.cshtml"
                                                    Write(Admin.TypeAd);

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 47 "..\..\Views\AdsOption\_Item.cshtml"
                                                                    Write(Model.Type == AdsType.Banner ? Admin.Banner : Admin.Slide);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"info-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"top-part\"");

WriteLiteral(">\r\n                    <a>\r\n                        <p>");

            
            #line 53 "..\..\Views\AdsOption\_Item.cshtml"
                      Write(Admin.Position);

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 53 "..\..\Views\AdsOption\_Item.cshtml"
                                        Write(Model.PositionType == AdsPositionType.AdsLandingPage ? Admin.MainPage : Admin.CategoriesPages);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"middle-part\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"small-state\"");

WriteLiteral("><span>");

            
            #line 57 "..\..\Views\AdsOption\_Item.cshtml"
                                            Write(Admin.Priority);

            
            #line default
            #line hidden
WriteLiteral(": </span>");

            
            #line 57 "..\..\Views\AdsOption\_Item.cshtml"
                                                                    Write(Model.Order);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"bottom-part\"");

WriteLiteral(">\r\n                    <p>\r\n                        <span>");

            
            #line 61 "..\..\Views\AdsOption\_Item.cshtml"
                         Write(Model.Price.CastToRegularCurrency());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        <span>");

            
            #line 62 "..\..\Views\AdsOption\_Item.cshtml"
                         Write(Admin.Toman);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    </p>\r\n                </div>\r\n            </div>\r\n  " +
"      </div>\r\n        <div");

WriteLiteral(" class=\"clearboth\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
