#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.CatalogSpecification
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    
    #line 2 "..\..\Views\CatalogSpecification\_Edit.cshtml"
    using Advertise.Core.Types;
    
    #line default
    #line hidden
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CatalogSpecification/_Edit.cshtml")]
    public partial class _Edit : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<IEnumerable<Advertise.Core.Models.CatalogSpecification.CatalogSpecificationViewModel>>
    {
        public _Edit()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\CatalogSpecification\_Edit.cshtml"
  
    var indexItem = 0;
    foreach (var productSpecification in Model)
    {
        switch (productSpecification.Type)
        {
            case SpecificationType.Droplist:

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"rl-label right-placed-label\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                          Write(productSpecification.Title);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 534), Tuple.Create("\"", 593)
, Tuple.Create(Tuple.Create("", 541), Tuple.Create("Specifications[", 541), true)
            
            #line 13 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 556), Tuple.Create<System.Object, System.Int32>(indexItem
            
            #line default
            #line hidden
, 556), false)
, Tuple.Create(Tuple.Create("", 566), Tuple.Create("].SpecificationOptionIdList", 566), true)
);

WriteLiteral(" class=\"left-placed-input\"");

WriteLiteral(">\r\n                        <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">-- ");

            
            #line 14 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                       Write(Admin.Choose);

            
            #line default
            #line hidden
WriteLiteral(" --</option>\r\n");

            
            #line 15 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                         foreach (var option in productSpecification.Options)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 835), Tuple.Create("\"", 853)
            
            #line 17 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 843), Tuple.Create<System.Object, System.Int32>(option.Id
            
            #line default
            #line hidden
, 843), false)
);

WriteLiteral(" ");

            
            #line 17 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                        if (productSpecification.SpecificationOptionIdList.Contains(option.Id)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" selected");

            
            #line 17 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                                                                                                                        }
            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 17 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                                                                                                                     Write(option.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 18 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n                </div>\r\n");

            
            #line 21 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                break;

            case SpecificationType.String:

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"rl-label right-placed-label\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                          Write(productSpecification.Title);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1315), Tuple.Create("\"", 1354)
, Tuple.Create(Tuple.Create("", 1322), Tuple.Create("Specifications[", 1322), true)
            
            #line 26 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1337), Tuple.Create<System.Object, System.Int32>(indexItem
            
            #line default
            #line hidden
, 1337), false)
, Tuple.Create(Tuple.Create("", 1347), Tuple.Create("].Value", 1347), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1355), Tuple.Create("\"", 1390)
            
            #line 26 "..\..\Views\CatalogSpecification\_Edit.cshtml"
      , Tuple.Create(Tuple.Create("", 1363), Tuple.Create<System.Object, System.Int32>(productSpecification.Value
            
            #line default
            #line hidden
, 1363), false)
);

WriteLiteral(" class=\"left-placed-input\"");

WriteLiteral("/>\r\n                </div>\r\n");

            
            #line 28 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                break;

            case SpecificationType.Checkbox:

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">");

            
            #line 32 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                       Write(productSpecification.Title);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 33 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                      
                        var indexCheckbox = 0;
                        foreach (var option in productSpecification.Options)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1995), Tuple.Create("\"", 2060)
, Tuple.Create(Tuple.Create("", 2002), Tuple.Create("Specifications[", 2002), true)
            
            #line 39 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2017), Tuple.Create<System.Object, System.Int32>(indexItem
            
            #line default
            #line hidden
, 2017), false)
, Tuple.Create(Tuple.Create("", 2027), Tuple.Create("].SpecificationOptionIdList.Index", 2027), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2061), Tuple.Create("\"", 2083)
            
            #line 39 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 2069), Tuple.Create<System.Object, System.Int32>(indexCheckbox
            
            #line default
            #line hidden
, 2069), false)
);

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("name", Tuple.Create(" name=\"", 2145), Tuple.Create("\"", 2220)
, Tuple.Create(Tuple.Create("", 2152), Tuple.Create("Specifications[", 2152), true)
            
            #line 40 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2167), Tuple.Create<System.Object, System.Int32>(indexItem
            
            #line default
            #line hidden
, 2167), false)
, Tuple.Create(Tuple.Create("", 2177), Tuple.Create("].SpecificationOptionIdList[", 2177), true)
            
            #line 40 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                      , Tuple.Create(Tuple.Create("", 2205), Tuple.Create<System.Object, System.Int32>(indexCheckbox
            
            #line default
            #line hidden
, 2205), false)
, Tuple.Create(Tuple.Create("", 2219), Tuple.Create("]", 2219), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2221), Tuple.Create("\"", 2239)
            
            #line 40 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                              , Tuple.Create(Tuple.Create("", 2229), Tuple.Create<System.Object, System.Int32>(option.Id
            
            #line default
            #line hidden
, 2229), false)
);

WriteLiteral(" ");

            
            #line 40 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                                                                                                                           if (productSpecification.SpecificationOptionIdList.Contains(option.Id)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked");

            
            #line 40 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                                                                                                                                                                                                                          }
            
            #line default
            #line hidden
WriteLiteral(" />\r\n                                    <span>");

            
            #line 41 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                     Write(option.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                </label>\r\n                            </" +
"div>\r\n");

            
            #line 44 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                            indexCheckbox = indexCheckbox + 1;
                        }
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 48 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                break;

            case SpecificationType.Color:
                break;

            case SpecificationType.Radiobox:

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">");

            
            #line 55 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                       Write(productSpecification.Title);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 56 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                      
                        var indexRadiobox = 0;
                        foreach (var option in productSpecification.Options)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" type=\"radio\"");

WriteAttribute("name", Tuple.Create(" name=\"", 3241), Tuple.Create("\"", 3300)
, Tuple.Create(Tuple.Create("", 3248), Tuple.Create("Specifications[", 3248), true)
            
            #line 62 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3263), Tuple.Create<System.Object, System.Int32>(indexItem
            
            #line default
            #line hidden
, 3263), false)
, Tuple.Create(Tuple.Create("", 3273), Tuple.Create("].SpecificationOptionIdList", 3273), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 3301), Tuple.Create("\"", 3319)
            
            #line 62 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                           , Tuple.Create(Tuple.Create("", 3309), Tuple.Create<System.Object, System.Int32>(option.Id
            
            #line default
            #line hidden
, 3309), false)
);

WriteLiteral(" ");

            
            #line 62 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                                                                                                        if (productSpecification.SpecificationOptionIdList.Contains(option.Id)) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" checked");

            
            #line 62 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                                                                                                                                                                                                                       }
            
            #line default
            #line hidden
WriteLiteral(" />\r\n                                    <span>");

            
            #line 63 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                                     Write(option.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                </label>\r\n                            </" +
"div>\r\n");

            
            #line 66 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                            indexRadiobox = indexRadiobox + 1;
                        }
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 70 "..\..\Views\CatalogSpecification\_Edit.cshtml"
                break;

            case SpecificationType.Currency:
                break;
        }

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 3838), Tuple.Create("\"", 3874)
, Tuple.Create(Tuple.Create("", 3845), Tuple.Create("Specifications[", 3845), true)
            
            #line 75 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3860), Tuple.Create<System.Object, System.Int32>(indexItem
            
            #line default
            #line hidden
, 3860), false)
, Tuple.Create(Tuple.Create("", 3870), Tuple.Create("].Id", 3870), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 3875), Tuple.Create("\"", 3907)
            
            #line 75 "..\..\Views\CatalogSpecification\_Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3883), Tuple.Create<System.Object, System.Int32>(productSpecification.Id
            
            #line default
            #line hidden
, 3883), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("        <hr");

WriteLiteral(" class=\"line-separator\"");

WriteLiteral(" />\r\n");

            
            #line 77 "..\..\Views\CatalogSpecification\_Edit.cshtml"
        indexItem = indexItem + 1;
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
