#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.ProductComment
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    
    #line 2 "..\..\Views\ProductComment\_Item.cshtml"
    using Advertise.Core.Extensions;
    
    #line default
    #line hidden
    using Advertise.Core.Languages;
    
    #line 3 "..\..\Views\ProductComment\_Item.cshtml"
    using Advertise.Service.Managers.File;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\ProductComment\_Item.cshtml"
    using Advertise.Service.Services.Permissions;
    
    #line default
    #line hidden
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ProductComment/_Item.cshtml")]
    public partial class _Item : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.ProductComment.ProductCommentViewModel>
    {
        public _Item()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"landing-items nov-item-height-032\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"product-item column landing-column\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"nov-item-header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"action-section without-share\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\ProductComment\_Item.cshtml"
                
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\ProductComment\_Item.cshtml"
                 if (User.IsInRole(PermissionConst.CanProductCommentMyEdit) || User.IsInRole(PermissionConst.CanProductCommentDeleteAjax) || User.IsInRole(PermissionConst.CanProductCommentEditApprove) || User.IsInRole(PermissionConst.CanProductCommentEditReject) || User.IsInRole(PermissionConst.CanUserViolationCreate))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"item-edit-wrapper\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-pencil-square\"");

WriteLiteral("></i>\r\n                        <ul");

WriteLiteral(" class=\"item-edit-list\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\ProductComment\_Item.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\ProductComment\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanProductCommentMyEdit))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1145), Tuple.Create("\"", 1198)
            
            #line 18 "..\..\Views\ProductComment\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 1152), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.ProductComment.Edit(Model.Id))
            
            #line default
            #line hidden
, 1152), false)
);

WriteLiteral(">\r\n                                        <span>");

            
            #line 19 "..\..\Views\ProductComment\_Item.cshtml"
                                         Write(Admin.Edit);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-pencil fa-flip-horizontal\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 23 "..\..\Views\ProductComment\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 24 "..\..\Views\ProductComment\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanProductCommentDeleteAjax))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" data-on-click=\"removeConfirm\"");

WriteLiteral(" data-param=\"");

            
            #line 27 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                       Write(Model.IsMine ? Url.Action(MVC.ProductComment.MyDeleteAjax(Model.Id)) : Url.Action(MVC.ProductComment.DeleteAjax(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                        <span>");

            
            #line 28 "..\..\Views\ProductComment\_Item.cshtml"
                                         Write(Admin.Delete);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-trash\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 32 "..\..\Views\ProductComment\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 33 "..\..\Views\ProductComment\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanProductCommentEditApprove))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" data-on-click=\"ajaxSimple\"");

WriteLiteral(" data-param=\"");

            
            #line 36 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                   Write(Url.Action(MVC.ProductComment.ApproveAjax(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                        <span>");

            
            #line 37 "..\..\Views\ProductComment\_Item.cshtml"
                                         Write(Admin.Approve);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-check-circle\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 41 "..\..\Views\ProductComment\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 42 "..\..\Views\ProductComment\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanProductCommentEditReject))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" data-on-click=\"ajaxSimple\"");

WriteLiteral(" data-param=\"");

            
            #line 45 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                   Write(Url.Action(MVC.ProductComment.RejectAjax(Model.Id)));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                        <span>");

            
            #line 46 "..\..\Views\ProductComment\_Item.cshtml"
                                         Write(Admin.Ignore);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-times-circle\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 50 "..\..\Views\ProductComment\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 51 "..\..\Views\ProductComment\_Item.cshtml"
                             if (User.IsInRole(PermissionConst.CanUserViolationCreate))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li>\r\n                                    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">\r\n                                        <span>");

            
            #line 55 "..\..\Views\ProductComment\_Item.cshtml"
                                         Write(Admin.Report);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        <i");

WriteLiteral(" class=\"fa fa-file-text-o\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</li>\r\n");

            
            #line 59 "..\..\Views\ProductComment\_Item.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </div>\r\n");

            
            #line 62 "..\..\Views\ProductComment\_Item.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"nov-item-body\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"image-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"product-preview-actions\"");

WriteLiteral(">\r\n                    <figure");

WriteLiteral(" class=\"product-preview-image\"");

WriteLiteral(">\r\n                        <a ");

            
            #line 69 "..\..\Views\ProductComment\_Item.cshtml"
                            if (Model.ProductImageFileName != null) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" href=\"");

            
            #line 69 "..\..\Views\ProductComment\_Item.cshtml"
                                                                              Write(Url.Action(MVC.Product.Detail(Model.ProductCode, Model.ProductTitle.Replace(" ","-"))));

            
            #line default
            #line hidden
WriteLiteral("\" ");

WriteLiteral(" ");

            
            #line 69 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                                                                    }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"item-preview-image\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4347), Tuple.Create("\"", 4511)
, Tuple.Create(Tuple.Create("", 4353), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 71 "..\..\Views\ProductComment\_Item.cshtml"
                                           if (Model.ProductImageFileName != null) {
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\ProductComment\_Item.cshtml"
                                                   WriteTo(__razor_attribute_value_writer, FileConst.ImagesWebPath.PlusWord(Model.ProductImageFileName));

            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                                              } else {
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                     WriteTo(__razor_attribute_value_writer, FileConst.NoPreview);

            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                                                                                       }
            
            #line default
            #line hidden
}), 4353), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 4512), Tuple.Create("\"", 4537)
            
            #line 71 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                               , Tuple.Create(Tuple.Create("", 4518), Tuple.Create<System.Object, System.Int32>(Model.ProductTitle
            
            #line default
            #line hidden
, 4518), false)
);

WriteLiteral(">\r\n                            </div>\r\n                        </a>\r\n            " +
"        </figure>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"caption-section\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"novinak-title-link\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4770), Tuple.Create("\"", 4860)
            
            #line 78 "..\..\Views\ProductComment\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 4777), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Product.Detail(Model.ProductCode, Model.ProductTitle.CastToSlug()))
            
            #line default
            #line hidden
, 4777), false)
);

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"novinak-title text-header\"");

WriteLiteral(">");

            
            #line 79 "..\..\Views\ProductComment\_Item.cshtml"
                                                    Write(Model.Body);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"info-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"top-part\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5082), Tuple.Create("\"", 5172)
            
            #line 84 "..\..\Views\ProductComment\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 5089), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Product.Detail(Model.ProductCode, Model.ProductTitle.CastToSlug()))
            
            #line default
            #line hidden
, 5089), false)
);

WriteLiteral(">\r\n                        <p>");

            
            #line 85 "..\..\Views\ProductComment\_Item.cshtml"
                      Write(Model.ProductTitle);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"middle-part\"");

WriteLiteral(">\r\n                    <p><i");

WriteLiteral(" class=\"fa fa-calendar-check-o\"");

WriteLiteral("></i> <span>");

            
            #line 89 "..\..\Views\ProductComment\_Item.cshtml"
                                                               Write(Admin.InsertDate.PlusWord(":"));

            
            #line default
            #line hidden
WriteLiteral("</span></p>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"bottom-part\"");

WriteLiteral(">\r\n                    <p>");

            
            #line 92 "..\..\Views\ProductComment\_Item.cshtml"
                  Write(Model.CreatedOn.CastToRegularDate());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"nov-item-footer\"");

WriteLiteral(">\r\n            <hr");

WriteLiteral(" class=\"line-separator item-footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"overview-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"image-part\"");

WriteLiteral(">\r\n                    <figure");

WriteLiteral(" class=\"user-avatar small\"");

WriteLiteral(">\r\n                        <a ");

            
            #line 101 "..\..\Views\ProductComment\_Item.cshtml"
                            if (Model.UserAvatar != null) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" href=\"");

            
            #line 101 "..\..\Views\ProductComment\_Item.cshtml"
                                                                    Write(Url.Action(MVC.User.Detail(Model.UserUserName)));

            
            #line default
            #line hidden
WriteLiteral("\" ");

WriteLiteral("   ");

            
            #line 101 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                     }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"novinak-image\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6089), Tuple.Create("\"", 6235)
, Tuple.Create(Tuple.Create("", 6095), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 103 "..\..\Views\ProductComment\_Item.cshtml"
                                           if (Model.UserAvatar != null) {
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\ProductComment\_Item.cshtml"
                                         WriteTo(__razor_attribute_value_writer, FileConst.ImagesWebPath.PlusWord(Model.UserAvatar));

            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                          } else {
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                 WriteTo(__razor_attribute_value_writer, FileConst.NoAvatarPth);

            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                                                                     }
            
            #line default
            #line hidden
}), 6095), false)
);

WriteAttribute("alt", Tuple.Create(" alt=\"", 6236), Tuple.Create("\"", 6264)
            
            #line 103 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                             , Tuple.Create(Tuple.Create("", 6242), Tuple.Create<System.Object, System.Int32>(Model.UserDisplayName
            
            #line default
            #line hidden
, 6242), false)
);

WriteLiteral(">\r\n                            </div>\r\n                        </a>\r\n            " +
"        </figure>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"caption-part\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6455), Tuple.Create("\"", 6510)
            
            #line 109 "..\..\Views\ProductComment\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 6462), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.User.Detail(Model.UserUserName))
            
            #line default
            #line hidden
, 6462), false)
);

WriteLiteral(" class=\"tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 6531), Tuple.Create("\"", 6561)
            
            #line 109 "..\..\Views\ProductComment\_Item.cshtml"
                          , Tuple.Create(Tuple.Create("", 6539), Tuple.Create<System.Object, System.Int32>(Model.UserDisplayName
            
            #line default
            #line hidden
, 6539), false)
);

WriteLiteral(">\r\n                        <p");

WriteLiteral(" class=\"text-header tiny\"");

WriteLiteral(">");

            
            #line 110 "..\..\Views\ProductComment\_Item.cshtml"
                                               Write(Model.UserFullName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </a>\r\n                </div>\r\n            </div>\r\n     " +
"       <div");

WriteLiteral(" class=\"toggle-section\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"likes-wrapper\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6839), Tuple.Create("\"", 6856)
            
            #line 116 "..\..\Views\ProductComment\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 6847), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 6847), false)
);

WriteLiteral(" name=\"commentId\"");

WriteLiteral(" id=\"commentId\"");

WriteLiteral(" />\r\n                    <p");

WriteLiteral(" class=\"product-detail-eh detail-heart tooltip\"");

WriteAttribute("title", Tuple.Create(" title=\"", 6963), Tuple.Create("\"", 6983)
            
            #line 117 "..\..\Views\ProductComment\_Item.cshtml"
, Tuple.Create(Tuple.Create("", 6971), Tuple.Create<System.Object, System.Int32>(Admin.Likes
            
            #line default
            #line hidden
, 6971), false)
);

WriteLiteral(">\r\n                        <a ");

            
            #line 118 "..\..\Views\ProductComment\_Item.cshtml"
                            if (User.Identity.IsAuthenticated) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" href=\"javascript:void(0)\" ");

WriteLiteral("   ");

            
            #line 118 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                            } else {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" href=\"");

            
            #line 118 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                             Write(Url.Action(MVC.Account.EmailRegister()));

            
            #line default
            #line hidden
WriteLiteral("\" ");

WriteLiteral("   ");

            
            #line 118 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                                                                                      }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            <i");

WriteAttribute("class", Tuple.Create(" class=\"", 7203), Tuple.Create("\"", 7289)
, Tuple.Create(Tuple.Create("", 7211), Tuple.Create("fa", 7211), true)
, Tuple.Create(Tuple.Create(" ", 7213), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 119 "..\..\Views\ProductComment\_Item.cshtml"
                                          if (Model.InitLike) {
            
            #line default
            #line hidden
WriteLiteralTo(__razor_attribute_value_writer, "fa-heart");

            
            #line 119 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                    } else {
            
            #line default
            #line hidden
WriteLiteralTo(__razor_attribute_value_writer, "fa-heart-o");

            
            #line 119 "..\..\Views\ProductComment\_Item.cshtml"
                                                                                                                   }
            
            #line default
            #line hidden
}), 7214), false)
);

WriteLiteral("></i>\r\n                            <span>");

            
            #line 120 "..\..\Views\ProductComment\_Item.cshtml"
                             Write(Model.LikeCount);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </a>\r\n                    </p>\r\n                " +
"    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div" +
"");

WriteLiteral(" class=\"clearboth\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
