#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.CompanyImage
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    
    #line 3 "..\..\Views\CompanyImage\Edit.cshtml"
    using Auth = Advertise.Service.Services.Permissions.PermissionConst;
    
    #line default
    #line hidden
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CompanyImage/Edit.cshtml")]
    public partial class Edit : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.CompanyImage.CompanyImageEditViewModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\CompanyImage\Edit.cshtml"
  
    Layout = Model.IsMine!= true ? MVC.Shared.Views.SiteLayout.Panel._PanelLayout : MVC.Shared.Views.SiteLayout.Profile._ProfileLayout;
    ViewBag.Title = Admin.ImageEdit;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"dashboard-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"headline buttons primary\"");

WriteLiteral(">\r\n        <h4>");

            
            #line 10 "..\..\Views\CompanyImage\Edit.cshtml"
       Write(Admin.ImageEdit);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"form-box-item profile-form\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"editCompanyImage\"");

WriteLiteral(" action=\"\"");

WriteLiteral(" method=\"Post\"");

WriteLiteral("  data-on-load=\"validateCompanyImage\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Views\CompanyImage\Edit.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 15 "..\..\Views\CompanyImage\Edit.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"Id\"");

WriteLiteral(" name=\"Id\"");

WriteAttribute("value", Tuple.Create(" value=\"", 769), Tuple.Create("\"", 786)
            
            #line 16 "..\..\Views\CompanyImage\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 777), Tuple.Create<System.Object, System.Int32>(Model.Id
            
            #line default
            #line hidden
, 777), false)
);

WriteLiteral(" />\r\n\r\n            <div");

WriteLiteral(" class=\"input-form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"vertical-dashed\"");

WriteLiteral("></div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"Title\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\CompanyImage\Edit.cshtml"
                                                   Write(Admin.Title);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Title\"");

WriteLiteral(" name=\"Title\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1497), Tuple.Create("\"", 1517)
            
            #line 32 "..\..\Views\CompanyImage\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1505), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 1505), false)
);

WriteAttribute("placeholder", Tuple.Create(" placeholder=\"", 1518), Tuple.Create("\"", 1544)
            
            #line 32 "..\..\Views\CompanyImage\Edit.cshtml"
                 , Tuple.Create(Tuple.Create("", 1532), Tuple.Create<System.Object, System.Int32>(Admin.Title
            
            #line default
            #line hidden
, 1532), false)
);

WriteLiteral(" class=\"tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1565), Tuple.Create("\"", 1596)
            
            #line 32 "..\..\Views\CompanyImage\Edit.cshtml"
                                                          , Tuple.Create(Tuple.Create("", 1573), Tuple.Create<System.Object, System.Int32>(Admin.ItShowsImageName
            
            #line default
            #line hidden
, 1573), false)
);

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"Order\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">اولویت</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Order\"");

WriteLiteral(" name=\"Order\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2231), Tuple.Create("\"", 2251)
            
            #line 46 "..\..\Views\CompanyImage\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2239), Tuple.Create<System.Object, System.Int32>(Model.Order
            
            #line default
            #line hidden
, 2239), false)
);

WriteLiteral(" placeholder=\"الویت\"");

WriteLiteral(" class=\"tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2292), Tuple.Create("\"", 2323)
            
            #line 46 "..\..\Views\CompanyImage\Edit.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 2300), Tuple.Create<System.Object, System.Int32>(Admin.ItShowsImageName
            
            #line default
            #line hidden
, 2300), false)
);

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"files\"");

WriteLiteral(" class=\"rl-label tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2891), Tuple.Create("\"", 2920)
            
            #line 59 "..\..\Views\CompanyImage\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2899), Tuple.Create<System.Object, System.Int32>(Admin.UploadingPhoto
            
            #line default
            #line hidden
, 2899), false)
);

WriteLiteral(">");

            
            #line 59 "..\..\Views\CompanyImage\Edit.cshtml"
                                                                                             Write(Admin.UploadingPhoto);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                    ");

            
            #line 60 "..\..\Views\CompanyImage\Edit.cshtml"
               Write(Html.Partial(MVC.Shared.Views.FineUploaderTemplates._FineUploaderTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" name=\"files\"");

WriteLiteral(" id=\"files\"");

WriteLiteral(" data-on-load=\"uploaderCompanyImage\"");

WriteLiteral(" data-param=\"edit\"");

WriteLiteral("></div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral("></div>\r\n            </div>\r\n        </form>\r\n        \r\n        <div");

WriteLiteral(" class=\"form-button-container\"");

WriteLiteral(">\r\n");

            
            #line 69 "..\..\Views\CompanyImage\Edit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\CompanyImage\Edit.cshtml"
             if (User.IsInRole(Auth.CanCompanyImageEditApprove) && Model.IsMine != true)
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" form=\"editCompanyImage\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"form-button right-form-btn ok-button round-corners-five disabled-btn-link" +
"\"");

WriteLiteral(" disabled=\"disabled\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 3600), Tuple.Create("\"", 3682)
, Tuple.Create(Tuple.Create("", 3610), Tuple.Create("javascript:", 3610), true)
, Tuple.Create(Tuple.Create(" ", 3621), Tuple.Create("form.action", 3622), true)
, Tuple.Create(Tuple.Create(" ", 3633), Tuple.Create("=", 3634), true)
, Tuple.Create(Tuple.Create(" ", 3635), Tuple.Create("\'", 3636), true)
            
            #line 71 "..\..\Views\CompanyImage\Edit.cshtml"
                                                                                                                        , Tuple.Create(Tuple.Create("", 3637), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.CompanyImage.EditApprove())
            
            #line default
            #line hidden
, 3637), false)
, Tuple.Create(Tuple.Create("", 3680), Tuple.Create("\';", 3680), true)
);

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-check-circle\"");

WriteLiteral("></i>\r\n                    <span>");

            
            #line 73 "..\..\Views\CompanyImage\Edit.cshtml"
                     Write(Admin.OkAndClose);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </button>\r\n");

WriteLiteral("                <button");

WriteLiteral(" form=\"editCompany\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"form-button right-form-btn ok-button round-corners-five disabled-btn-link" +
"\"");

WriteLiteral(" disabled=\"disabled\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 3979), Tuple.Create("\"", 4060)
, Tuple.Create(Tuple.Create("", 3989), Tuple.Create("javascript:", 3989), true)
, Tuple.Create(Tuple.Create(" ", 4000), Tuple.Create("form.action", 4001), true)
, Tuple.Create(Tuple.Create(" ", 4012), Tuple.Create("=", 4013), true)
, Tuple.Create(Tuple.Create(" ", 4014), Tuple.Create("\'", 4015), true)
            
            #line 75 "..\..\Views\CompanyImage\Edit.cshtml"
                                                                                                                   , Tuple.Create(Tuple.Create("", 4016), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.CompanyImage.EditReject())
            
            #line default
            #line hidden
, 4016), false)
, Tuple.Create(Tuple.Create("", 4058), Tuple.Create("\';", 4058), true)
);

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-times-circle\"");

WriteLiteral("></i>\r\n                    <span>");

            
            #line 77 "..\..\Views\CompanyImage\Edit.cshtml"
                     Write(Admin.CancelAndClose);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </button>\r\n");

            
            #line 79 "..\..\Views\CompanyImage\Edit.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" form=\"editCompanyImage\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"form-button right-form-btn ok-button round-corners-five disabled-btn-link" +
"\"");

WriteLiteral(" disabled=\"disabled\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 4414), Tuple.Create("\"", 4491)
, Tuple.Create(Tuple.Create("", 4424), Tuple.Create("javascript:", 4424), true)
, Tuple.Create(Tuple.Create(" ", 4435), Tuple.Create("form.action", 4436), true)
, Tuple.Create(Tuple.Create(" ", 4447), Tuple.Create("=", 4448), true)
, Tuple.Create(Tuple.Create(" ", 4449), Tuple.Create("\'", 4450), true)
            
            #line 82 "..\..\Views\CompanyImage\Edit.cshtml"
                                                                                                                        , Tuple.Create(Tuple.Create("", 4451), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.CompanyImage.MyEdit())
            
            #line default
            #line hidden
, 4451), false)
, Tuple.Create(Tuple.Create("", 4489), Tuple.Create("\';", 4489), true)
);

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-save\"");

WriteLiteral("></i>\r\n                    <span>");

            
            #line 84 "..\..\Views\CompanyImage\Edit.cshtml"
                     Write(Admin.Save);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </button>\r\n");

            
            #line 86 "..\..\Views\CompanyImage\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
