#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Shared.SiteMapTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SiteMapTemplates/SiteMapNodeModel.cshtml")]
    public partial class SiteMapNodeModel : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<SiteMapNodeModel>
    {
        public SiteMapNodeModel()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
 if (Model.IsCurrentNode && Model.SourceMetadata["HtmlHelper"].ToString() != "MvcSiteMapProvider.Web.Html.MenuHelper")
{ 

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 5 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 6 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
}
else if (Model.IsClickable)
{ 
    if (string.IsNullOrEmpty(Model.Description))
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 326), Tuple.Create("\"", 343)
            
            #line 11 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
, Tuple.Create(Tuple.Create("", 333), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 333), false)
);

WriteLiteral(">");

            
            #line 11 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
                        Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");

            
            #line 12 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 393), Tuple.Create("\"", 410)
            
            #line 15 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
, Tuple.Create(Tuple.Create("", 400), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 400), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 411), Tuple.Create("\"", 437)
            
            #line 15 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
, Tuple.Create(Tuple.Create("", 419), Tuple.Create<System.Object, System.Int32>(Model.Description
            
            #line default
            #line hidden
, 419), false)
);

WriteLiteral(">");

            
            #line 15 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
                                                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");

            
            #line 16 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
    }
}
else
{ 

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
     Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("\n");

            
            #line 21 "..\..\Views\Shared\SiteMapTemplates\SiteMapNodeModel.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
