#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Product/_CatalogAddButton.cshtml")]
    public partial class _Views_Product__CatalogAddButton_cshtml : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public _Views_Product__CatalogAddButton_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"catalogItem round-corners-five\"");

WriteLiteral(" data-on-click=\"addCatalogCreate\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"catalog-add-shadow round-corners-five\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"catalog-product-add round-corners-five\"");

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-plus-circle\"");

WriteLiteral("></i>\r\n        <i");

WriteLiteral(" class=\"fa fa-plus\"");

WriteLiteral("></i>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"input-container nov-seven-col nov-col-1\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"rl-label catalog-temp-label\"");

WriteLiteral(">\r\n            <span>");

            
            #line 9 "..\..\Views\Product\_CatalogAddButton.cshtml"
             Write(Admin.Category2);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </label>\r\n        <select disabled></select>\r\n    </div>\r\n    <d" +
"iv");

WriteLiteral(" class=\"input-container nov-seven-col nov-col-2\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"rl-label catalog-temp-label\"");

WriteLiteral(">\r\n            <span>کالا</span>\r\n        </label>\r\n        <select disabled></se" +
"lect>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"input-container nov-seven-col nov-col-3\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"rl-label catalog-temp-label\"");

WriteLiteral(">\r\n            <span>");

            
            #line 21 "..\..\Views\Product\_CatalogAddButton.cshtml"
             Write(Admin.Color);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </label>\r\n        <select disabled></select>\r\n    </div>\r\n    <d" +
"iv");

WriteLiteral(" class=\"input-container nov-seven-col nov-col-4\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"rl-label catalog-temp-label\"");

WriteLiteral(">\r\n            <span>");

            
            #line 27 "..\..\Views\Product\_CatalogAddButton.cshtml"
             Write(Admin.Guarantee);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </label>\r\n        <select disabled></select>\r\n    </div>\r\n    <d" +
"iv");

WriteLiteral(" class=\"input-container nov-seven-col nov-col-5\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"rl-label catalog-temp-label\"");

WriteLiteral(">\r\n            <span>");

            
            #line 33 "..\..\Views\Product\_CatalogAddButton.cshtml"
             Write(Admin.Price);

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 33 "..\..\Views\Product\_CatalogAddButton.cshtml"
                           Write(Admin.Toman);

            
            #line default
            #line hidden
WriteLiteral(")</span>\r\n        </label>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"input-container nov-seven-col nov-col-6\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"rl-label catalog-temp-label\"");

WriteLiteral(">\r\n            <span>");

            
            #line 39 "..\..\Views\Product\_CatalogAddButton.cshtml"
             Write(Admin.Available);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </label>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" disabled />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"input-container nov-seven-col nov-col-7\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"rl-label catalog-temp-label\"");

WriteLiteral(">\r\n            <span>");

            
            #line 45 "..\..\Views\Product\_CatalogAddButton.cshtml"
             Write(Admin.State);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </label>\r\n        <select disabled></select>\r\n    </div>\r\n    <d" +
"iv");

WriteLiteral(" class=\"input-container\"");

WriteLiteral("></div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
