#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.AdsPayment
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AdsPayment/Complete.cshtml")]
    public partial class Complete : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public Complete()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\AdsPayment\Complete.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Public._PublicLayout;
    ViewBag.Title = " خرید تبلیغ موفقیت آمیز!";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"mp-wrapper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"mp-container\"");

WriteLiteral(">\r\n        <h1");

WriteLiteral(" class=\"mp-header mp-msg\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-check-circle-o\"");

WriteLiteral("></i>\r\n            <span");

WriteLiteral(" class=\"mp-msg\"");

WriteLiteral("> تبلیغ مورد نظر شما با موفقیت خریداری شد!</span>\r\n        </h1>\r\n        <h2");

WriteLiteral(" class=\"mp-paragraph\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-cart-plus fa-flip-horizontal mp-icon\"");

WriteLiteral("></i>\r\n            <span>");

            
            #line 14 "..\..\Views\AdsPayment\Complete.cshtml"
             Write(Admin.MessageSuccessfulPlanPurchase);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 601), Tuple.Create("\"", 644)
            
            #line 15 "..\..\Views\AdsPayment\Complete.cshtml"
, Tuple.Create(Tuple.Create("", 608), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Profile.Dashboard())
            
            #line default
            #line hidden
, 608), false)
);

WriteLiteral(" class=\"mp-link\"");

WriteLiteral(">\r\n                <span>");

            
            #line 16 "..\..\Views\AdsPayment\Complete.cshtml"
                 Write(Admin.ReturnToTheProfiePage);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </a>\r\n        </h2>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
