#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Page/Policy.cshtml")]
    public partial class Policy : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public Policy()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Page\Policy.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Public._PublicLayout;
    ViewBag.Title = Admin.RulesAndRegulations;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"section-wrap\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"section overflowable\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"headline pages-headline simple primary\"");

WriteLiteral(">\r\n            <h1>\r\n                <i");

WriteLiteral(" class=\"fa fa-gavel\"");

WriteLiteral("></i> \r\n");

WriteLiteral("                ");

            
            #line 11 "..\..\Views\Page\Policy.cshtml"
           Write(Admin.RulesAndRegulations);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </h1>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"pages-container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pages-cont-wrap\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pages-conts\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">در این بخش ما شما را با قوانین مجموعه نویناک آشنا می‌کنیم تا بتوانیم در شرایط و " +
"بستری مناسب معاملات خود را انجام دهیم. مجموعه قوانینی که ما برای مجموعه نویناک پ" +
"یش‌بینی و تنظیم نموده‌ایم، در دو دسته که شامل <span");

WriteLiteral(" class=\"page-red\"");

WriteLiteral(">«مشتریان»</span> و <span");

WriteLiteral(" class=\"page-red\"");

WriteLiteral(">«صاحبان کسب و کار»</span> می‌شود گردآوری شده‌اند و لذا در ابتدا نیاز می‌دانیم تا" +
" نعریف خود را از این دو دسته ارائه نماییم:</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral("><span");

WriteLiteral(" class=\"page-red\"");

WriteLiteral(">1- مشتری:</span> هر شخصی که اطلاعات کاربری خود را نویناک ثبت کرده و اقدام به انج" +
"ام یک معامله نموده باشد.</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral("><span");

WriteLiteral(" class=\"page-red\"");

WriteLiteral(">2- صاحب کسب و کار:</span> شامل هر شخص حقیقی یا مجموعه حقوقی که کالایی مجاز و غیر" +
" قاچاق یا محصولی تولید داخل را برای فروش عرضه نموده و یا خدمتی برای ارائه و انجا" +
"م داشته باشد.</p>\r\n                    <p");

WriteLiteral(" class=\"rule-title\"");

WriteLiteral(">قوانین مربوط به صاحبان کسب و کار:</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(@">با توجه به تعریف بالا و نیز به‌منظور جلوگیری و پیش‌بینی هرگونه سوء رفتار در رابطه با فروش کالا و نیز مسئولیت‌پذیری فروشنده و احترام به حقوق خریدار، نویناک در ازای صفحات رسمی (official) به فروشندگان، مدارک و اعتبار ایشان را اخذ نموده تا بدین وسیله برای مشتریان و بازدیدکنندگان صفحه ایشان در نویناک، نوعی اعتماد صورت گیرد. و اما قوانینی که فروشنده در نویناک ملزم به رعایت آن‌ها می‌باشد، عبارتند از:</p>
                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral("><span");

WriteLiteral(" class=\"page-red\"");

WriteLiteral(">تذکر:</span> درنهایت نویناک اختیار دارد که نام انتخابی را تأیید یا رد نماید.</p>" +
"\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">2- صاحبان کسب و کار می‌بایست اطلاعات خود را واقعی (و نه به‌صورت مستعار) ارائه نم" +
"ایند تا هنگام ارائه مدارک مشکلی حهت تأیید مدارک وجود نداشته باشد.</p>\r\n         " +
"           <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(@">3- خدمات و کالاهایی که هر شرکت یا فروشگاه ارائه می‌نمایند شامل عکس، ویدیو و محتوای متنی و یا هرگونه فایل دیگری نباید حاوی مسائل خلاف شرع و قوانین و مقررات نظام جمهور اسلامی ایران، خلاف عرف و اخلاق جامعه بوده و یا توهین‌آمیز تلقی گردند.</p>
                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral("><span");

WriteLiteral(" class=\"page-red\"");

WriteLiteral(">تذکر:</span> نویناک مجاز می‌باشد تا در ابتدا کالا و خدمات مورد ارائه را بررسی نم" +
"وده و سپس آن‌ها را تأیید و یا رد نماید.</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(@">4- صاحب کسب و کار می‌بایست اطلاعات دقیق، معتبر و مطابق واقع را راجع به خدمت و کالای خود ارائه نماید و در غیر این‌صورت چنانچه جنس فروخته شده به خریدار مطابق با اطلاعات مندرج در نویناک نباشد، عواقب بازگشت کالا و هزینه‌های جاری آن برعهده فروشنده می‌باشد (فروشنده موظف است نسبت به تأمین کالای مذکور اقدام نماید).</p>
                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">5- فروشنده کالا می‌بایست از کالای خود حداقل یک عدد عکس در سامانه قرار دهد و درغی" +
"ر ای‌صورت آن کالا تأیید نخواهد شد.</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">6- کاربران عادی و صاحبان کسب و کار می‌بایست نسبت ابراز عقیده دیگران برخورد مؤدبا" +
"نه و محترمانه داشته باشند.</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">7- صاحبان کسب و کار موظف‌اند تا هر زمان که تغییری در نشانی، شماره تماس و یا شمار" +
"ه حساب‌شان ایجاد گردید، آن را به اطلاع تیم نویناک برسانند تا مسکلی در روند و انج" +
"ام معاملات یا خدمات نویناک به ایشان پیش نیاید.</p>\r\n                    <p");

WriteLiteral(" class=\"rule-title\"");

WriteLiteral(">قوانین مربوط به مشتریان:</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(@">1- چنانچه کاربر کالایی را خریداری نموده و آن کالا با مشخصات مندرج در صفحه فروشگاه مطابقت نداشته باشد، خریدار می‌تواند کالای مورد نظر را ظرف 7 روز از تاریخ تحویل کالا به ایشان، مرجوع نماید و در ضمن فروشنده نیز موظف به تأمین کالای اصلی و مطابق با مشخصات بیان شده در صفحه خود می‌باشد.</p>
                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">2- خریدار می‌بایست در «تکمیل فرایند خرید» خود، نشانی دقیق و نیز نام شخص تحویل گی" +
"رنده کالا را به‌صورت دقیق وارد نماید تا مشکلی در فرایند ارسال کالا ایجاد نشود.</" +
"p>\r\n                    <p");

WriteLiteral(" class=\"rule-title\"");

WriteLiteral(">حفظ حریم شخصی:</p>\r\n                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">مجموعه نویناک در راستای صیانت و احترام به حریم شخصی افراد، سیاست‌های زیادی را در" +
" راستای برآورده‌سازی رضایت و اعتماد کاربران خود به کار بسته است.</p>\r\n          " +
"          <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(@">بهتر است بدانبد که نویناک چگونه اطلاعاتی را جمع‌آوری و استفاده می‌نماید! هنگام ثبت‌نام و پیویستن به نویناک، اطلاعاتی نظیر نام، نام خانوادگی، اطلاعات تماس، شماره حساب یا کارت بانکی و اطلاعاتی از این قبیل را در صورت تمایل در اختیار ما قرار می‌دهید تا ما نیز بتوانیم شما را در استفاده یا خریدی مناسب همراهی نماییم که این اطلاعات شما نزد ما به امانت حفظ خواهد گردید.</p>
                    <p");

WriteLiteral(" class=\"rule-p\"");

WriteLiteral(">این اطلاعات تحت هیچ شرایطی فاش نخواهند شد، مگر به درخواست مراجع و مقامات قضایی و" +
" در راستای پیگیری اموری مانند کلاهبرداری، حقوقی و جنایی.</p>\r\n                </" +
"div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
