// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _FineUploaderTemplate = "_FineUploaderTemplate";
                public readonly string _Footer = "_Footer";
                public readonly string _HeaderAnonymous = "_HeaderAnonymous";
                public readonly string _MainMenu = "_MainMenu";
                public readonly string _Noty = "_Noty";
                public readonly string _Paging = "_Paging";
                public readonly string _ProfileHeader = "_ProfileHeader";
                public readonly string _ProfileLayout = "_ProfileLayout";
                public readonly string _ProfileMenu = "_ProfileMenu";
                public readonly string _PublicLayout = "_PublicLayout";
                public readonly string _PublicSubscribe = "_PublicSubscribe";
                public readonly string _Script = "_Script";
                public readonly string _SideMenuHeader = "_SideMenuHeader";
                public readonly string _SideMenuLeft = "_SideMenuLeft";
                public readonly string _SideMenuRight = "_SideMenuRight";
                public readonly string _SideMenuRightAnonymous = "_SideMenuRightAnonymous";
                public readonly string _ViewType = "_ViewType";
                public readonly string CheckBoxListBuilder = "CheckBoxListBuilder";
                public readonly string DatePickerInitial = "DatePickerInitial";
                public readonly string NotyBuilder = "NotyBuilder";
                public readonly string SearchItem = "SearchItem";
            }
            public readonly string _FineUploaderTemplate = "~/Views/Shared/_FineUploaderTemplate.cshtml";
            public readonly string _Footer = "~/Views/Shared/_Footer.cshtml";
            public readonly string _HeaderAnonymous = "~/Views/Shared/_HeaderAnonymous.cshtml";
            public readonly string _MainMenu = "~/Views/Shared/_MainMenu.cshtml";
            public readonly string _Noty = "~/Views/Shared/_Noty.cshtml";
            public readonly string _Paging = "~/Views/Shared/_Paging.cshtml";
            public readonly string _ProfileHeader = "~/Views/Shared/_ProfileHeader.cshtml";
            public readonly string _ProfileLayout = "~/Views/Shared/_ProfileLayout.cshtml";
            public readonly string _ProfileMenu = "~/Views/Shared/_ProfileMenu.cshtml";
            public readonly string _PublicLayout = "~/Views/Shared/_PublicLayout.cshtml";
            public readonly string _PublicSubscribe = "~/Views/Shared/_PublicSubscribe.cshtml";
            public readonly string _Script = "~/Views/Shared/_Script.cshtml";
            public readonly string _SideMenuHeader = "~/Views/Shared/_SideMenuHeader.cshtml";
            public readonly string _SideMenuLeft = "~/Views/Shared/_SideMenuLeft.cshtml";
            public readonly string _SideMenuRight = "~/Views/Shared/_SideMenuRight.cshtml";
            public readonly string _SideMenuRightAnonymous = "~/Views/Shared/_SideMenuRightAnonymous.cshtml";
            public readonly string _ViewType = "~/Views/Shared/_ViewType.cshtml";
            public readonly string CheckBoxListBuilder = "~/Views/Shared/CheckBoxListBuilder.cshtml";
            public readonly string DatePickerInitial = "~/Views/Shared/DatePickerInitial.cshtml";
            public readonly string NotyBuilder = "~/Views/Shared/NotyBuilder.cshtml";
            public readonly string SearchItem = "~/Views/Shared/SearchItem.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
