#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Complaint
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Complaint/Detail.cshtml")]
    public partial class Detail : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.Complaint.ComplaintDetailViewModel>
    {
        public Detail()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Complaint\Detail.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Panel._PanelLayout;
    ViewBag.Title = Admin.RegisterComplaints;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"dashboard-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"headline buttons primary\"");

WriteLiteral(">\r\n        <h4>");

            
            #line 9 "..\..\Views\Complaint\Detail.cshtml"
       Write(Admin.RegisterComplaints);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" for=\"Title\"");

WriteLiteral(" class=\"rl-label tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 456), Tuple.Create("\"", 492)
            
            #line 12 "..\..\Views\Complaint\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 464), Tuple.Create<System.Object, System.Int32>(Admin.ItShowsComplaintTitle
            
            #line default
            #line hidden
, 464), false)
);

WriteLiteral(">");

            
            #line 12 "..\..\Views\Complaint\Detail.cshtml"
                                                                                        Write(Admin.Title);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Title\"");

WriteLiteral(" rows=\"1\"");

WriteLiteral(" cols=\"1\"");

WriteLiteral(" style=\"height: 50px; width: 400px; \"");

WriteAttribute("value", Tuple.Create(" value=\"", 608), Tuple.Create("\"", 628)
            
            #line 13 "..\..\Views\Complaint\Detail.cshtml"
                     , Tuple.Create(Tuple.Create("", 616), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 616), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" for=\"Body\"");

WriteLiteral(" class=\"rl-label tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 735), Tuple.Create("\"", 770)
            
            #line 16 "..\..\Views\Complaint\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 743), Tuple.Create<System.Object, System.Int32>(Admin.ItShowsComplaintText
            
            #line default
            #line hidden
, 743), false)
);

WriteLiteral(">");

            
            #line 16 "..\..\Views\Complaint\Detail.cshtml"
                                                                                      Write(Admin.Explanations);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Body\"");

WriteAttribute("value", Tuple.Create(" value=\"", 837), Tuple.Create("\"", 856)
            
            #line 17 "..\..\Views\Complaint\Detail.cshtml"
, Tuple.Create(Tuple.Create("", 845), Tuple.Create<System.Object, System.Int32>(Model.Body
            
            #line default
            #line hidden
, 845), false)
);

WriteLiteral(" rows=\"5\"");

WriteLiteral(" cols=\"20\"");

WriteLiteral(" style=\"height: 200px; width: 400px;\"");

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral("></div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
