#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.CompanyBalance
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CompanyBalance/Create.cshtml")]
    public partial class Create : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.CompanyBalance.CompanyBalanceCreateViewModel>
    {
        public Create()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\CompanyBalance\Create.cshtml"
  
    Layout = MVC.Shared.Views.SiteLayout.Panel._PanelLayout;
    ViewBag.Title = "ایجاد تسویه حساب";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"dashboard-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"headline buttons primary\"");

WriteLiteral(">\r\n        <h4>ایجاد تسویه حساب</h4>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-box-item profile-form\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"newCompanyBalance\"");

WriteAttribute("action", Tuple.Create(" action=\"", 445), Tuple.Create("\"", 494)
            
            #line 13 "..\..\Views\CompanyBalance\Create.cshtml"
, Tuple.Create(Tuple.Create("", 454), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.CompanyBalance.Create())
            
            #line default
            #line hidden
, 454), false)
);

WriteLiteral(" method=\"Post\"");

WriteLiteral(" data-on-load=\"validateCompanyBalance\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 14 "..\..\Views\CompanyBalance\Create.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            <div");

WriteLiteral(" class=\"input-form\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"vertical-dashed\"");

WriteLiteral("></div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"SettingTransactionId\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">\r\n                        <span>شماره حساب</span>\r\n                        <i");

WriteLiteral(" class=\"fa fa-question-circle tooltipster\"");

WriteLiteral(" title=\"شرکت\"");

WriteLiteral("></i>\r\n                    </label>\r\n                    <select");

WriteLiteral(" id=\"SettingTransactionId\"");

WriteLiteral(" name=\"SettingTransactionId\"");

WriteLiteral(">\r\n                        <option>--- ");

            
            #line 34 "..\..\Views\CompanyBalance\Create.cshtml"
                               Write(Admin.Choose);

            
            #line default
            #line hidden
WriteLiteral(" ---</option>\r\n");

            
            #line 35 "..\..\Views\CompanyBalance\Create.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\CompanyBalance\Create.cshtml"
                         foreach (var transaction in Model.SettingTransactionList)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1687), Tuple.Create("\"", 1713)
            
            #line 37 "..\..\Views\CompanyBalance\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1695), Tuple.Create<System.Object, System.Int32>(transaction.Value
            
            #line default
            #line hidden
, 1695), false)
);

WriteLiteral(" ");

            
            #line 37 "..\..\Views\CompanyBalance\Create.cshtml"
                                                                if (Model.SettingTransactionId.ToString() == transaction.Value){
            
            #line default
            #line hidden
WriteLiteral(" selected");

            
            #line 37 "..\..\Views\CompanyBalance\Create.cshtml"
                                                                                                                                                      }
            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 37 "..\..\Views\CompanyBalance\Create.cshtml"
                                                                                                                                                   Write(transaction.Text);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 38 "..\..\Views\CompanyBalance\Create.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n                </div>\r\n                \r\n        " +
"        <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"CompanyId\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">\r\n                        <span>شرکت</span>\r\n                        <i");

WriteLiteral(" class=\"fa fa-question-circle tooltipster\"");

WriteLiteral(" title=\"شرکت\"");

WriteLiteral("></i>\r\n                    </label>\r\n                    <select");

WriteLiteral(" id=\"CompanyId\"");

WriteLiteral(" name=\"CompanyId\"");

WriteLiteral(">\r\n                        <option>--- ");

            
            #line 57 "..\..\Views\CompanyBalance\Create.cshtml"
                               Write(Admin.Choose);

            
            #line default
            #line hidden
WriteLiteral(" ---</option>\r\n");

            
            #line 58 "..\..\Views\CompanyBalance\Create.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\CompanyBalance\Create.cshtml"
                         foreach (var company in Model.CompanyList)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2866), Tuple.Create("\"", 2888)
            
            #line 60 "..\..\Views\CompanyBalance\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2874), Tuple.Create<System.Object, System.Int32>(company.Value
            
            #line default
            #line hidden
, 2874), false)
);

WriteLiteral(" ");

            
            #line 60 "..\..\Views\CompanyBalance\Create.cshtml"
                                                            if (Model.CompanyId.ToString() == company.Value){
            
            #line default
            #line hidden
WriteLiteral(" selected");

            
            #line 60 "..\..\Views\CompanyBalance\Create.cshtml"
                                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 60 "..\..\Views\CompanyBalance\Create.cshtml"
                                                                                                                                Write(company.Text);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 61 "..\..\Views\CompanyBalance\Create.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </select>\r\n                </div>\r\n                \r\n        " +
"        <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"IssueTracking\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">شماره پیگیری</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"IssueTracking\"");

WriteLiteral(" name=\"IssueTracking\"");

WriteLiteral(" placeholder=\"شماره پیگیری\"");

WriteLiteral(" class=\"tooltipster\"");

WriteLiteral(" title=\"شماره پیگیری\"");

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"DocumentNumber\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">شماره سند</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DocumentNumber\"");

WriteLiteral(" name=\"DocumentNumber\"");

WriteLiteral(" placeholder=\"شماره سند\"");

WriteLiteral(" class=\"tooltipster\"");

WriteLiteral(" title=\"شماره سند\"");

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"Depositor\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">واریز کننده</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Depositor\"");

WriteLiteral(" name=\"Depositor\"");

WriteLiteral(" placeholder=\"واریز کننده\"");

WriteLiteral(" class=\"tooltipster\"");

WriteLiteral(" title=\"واریز کننده\"");

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"Amount\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">مبلغ تراکنش</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Amount\"");

WriteLiteral(" name=\"Amount\"");

WriteLiteral(" placeholder=\"مبلغ تراکنش\"");

WriteLiteral(" class=\"tooltipster\"");

WriteLiteral(" title=\"مبلغ تراکنش\"");

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"TransactionedOn\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">تاریخ تراکنش</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TransactionedOn\"");

WriteLiteral(" name=\"TransactionedOn\"");

WriteLiteral(" placeholder=\"تاریخ تراکنش\"");

WriteLiteral(" class=\"tooltipster\"");

WriteLiteral(" title=\"تاریخ تراکنش\"");

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"Description\"");

WriteLiteral(" class=\"rl-label\"");

WriteLiteral(">توضیحات</label>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Description\"");

WriteLiteral(" name=\"Description\"");

WriteLiteral(" placeholder=\"توضیحات\"");

WriteLiteral(" class=\"tooltipster\"");

WriteLiteral(" title=\"توضیحات\"");

WriteLiteral("/>\r\n                </div>\r\n                \r\n                <div");

WriteLiteral(" class=\"msg-container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"msg-box regular round-corners-five\"");

WriteLiteral(">\r\n                        <p>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-right\"");

WriteLiteral("></i>\r\n                            <span></span>\r\n                            <i");

WriteLiteral(" class=\"fa fa-quote-left\"");

WriteLiteral("></i>\r\n                        </p>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"input-container fixed-height\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"files\"");

WriteLiteral(" class=\"rl-label tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7941), Tuple.Create("\"", 7970)
            
            #line 159 "..\..\Views\CompanyBalance\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7949), Tuple.Create<System.Object, System.Int32>(Admin.ItChoosesImage
            
            #line default
            #line hidden
, 7949), false)
);

WriteLiteral(">");

            
            #line 159 "..\..\Views\CompanyBalance\Create.cshtml"
                                                                                             Write(Admin.UploadImage);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

WriteLiteral("                    ");

            
            #line 160 "..\..\Views\CompanyBalance\Create.cshtml"
               Write(Html.Partial(MVC.Shared.Views.FineUploaderTemplates._FineUploaderTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" name=\"files\"");

WriteLiteral(" id=\"files\"");

WriteLiteral(" data-on-load=\"uploaderCompanyBalance\"");

WriteLiteral("></div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"input-container\"");

WriteLiteral("></div>\r\n            </div>\r\n        </form>\r\n        \r\n        <div");

WriteLiteral(" class=\"form-button-container\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" form=\"newCompanyBalance\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"form-button right-form-btn ok-button round-corners-five disabled-btn-link" +
"\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-save\"");

WriteLiteral("></i>\r\n                <span>");

            
            #line 171 "..\..\Views\CompanyBalance\Create.cshtml"
                 Write(Admin.Save);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </button>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
