#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.CompanySocial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CompanySocial/_Item.cshtml")]
    public partial class _Item : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<Advertise.Core.Models.CompanySocial.CompanySocialViewModel>
    {
        public _Item()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"post-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"post-paragraph\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" class=\"post-title\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-check-circle-o\"");

WriteLiteral("></i>\r\n        </h3>\r\n        <p>\r\n");

WriteLiteral("            ");

            
            #line 9 "..\..\Views\CompanySocial\_Item.cshtml"
       Write(Model.CompanyTitle);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
