#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Shared.SiteLayout.Profile
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using Advertise.Web.Views.Shared.SiteLayout;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SiteLayout/Profile/_ProfileLayout.cshtml")]
    public partial class _ProfileLayout : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public _ProfileLayout()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"fa-IR\"");

WriteLiteral(" prefix=\"og: http://ogp.me/ns#\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <title>");

            
            #line 6 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteAttribute("content", Tuple.Create(" content=\"", 217), Tuple.Create("\"", 244)
            
            #line 7 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
, Tuple.Create(Tuple.Create("", 227), Tuple.Create<System.Object, System.Int32>(ViewBag.Keywords
            
            #line default
            #line hidden
, 227), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 276), Tuple.Create("\"", 306)
            
            #line 8 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
, Tuple.Create(Tuple.Create("", 286), Tuple.Create<System.Object, System.Int32>(ViewBag.Description
            
            #line default
            #line hidden
, 286), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteAttribute("content", Tuple.Create(" content=\"", 333), Tuple.Create("\"", 359)
            
            #line 9 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
, Tuple.Create(Tuple.Create("", 343), Tuple.Create<System.Object, System.Int32>(Admin.SiteTitle
            
            #line default
            #line hidden
, 343), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"language\"");

WriteLiteral(" content=\"fa-IR,en-US\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"document-type\"");

WriteLiteral(" content=\"Public\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"document-rating\"");

WriteLiteral(" content=\"General\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale" +
"=1.0, user-scalable=no\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"apple-touch-fullscreen\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"place:location:latitude\"");

WriteLiteral(" content=\"35.6989079\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"place:location:longitude\"");

WriteLiteral(" content=\"51.3916988\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"business:contact_data:locality\"");

WriteLiteral(" content=\"تهران\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"business:contact_data:country_name\"");

WriteLiteral(" content=\"ایران\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"business:contact_data:phone_number\"");

WriteLiteral(" content=\"+98 21 66489436\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"business:contact_data:website\"");

WriteLiteral(" content=\"http://Novinak.com\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"business:contact_data:email\"");

WriteLiteral(" content=\"info@novinak.com\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:site_name\"");

WriteLiteral(" content=\"NOVINAK\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" property=\"og:title\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1435), Tuple.Create("\"", 1459)
            
            #line 25 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1445), Tuple.Create<System.Object, System.Int32>(ViewBag.Title
            
            #line default
            #line hidden
, 1445), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" property=\"og:description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 1498), Tuple.Create("\"", 1528)
            
            #line 26 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1508), Tuple.Create<System.Object, System.Int32>(ViewBag.Description
            
            #line default
            #line hidden
, 1508), false)
);

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"application-name\"");

WriteLiteral(" content=\"Novinak\"");

WriteLiteral("/>\r\n    <meta");

WriteLiteral(" name=\"msapplication-TileColor\"");

WriteLiteral(" content=\"#f00c0c\"");

WriteLiteral("/>\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" href=\"/favicon.ico\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 30 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(RenderSection("og", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(Styles.Render("~/bundles/panelstyles/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 32 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(RenderSection("styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n");

            
            #line 35 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
 if (ViewBag.PageName != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" id=\"PageName\"");

WriteLiteral(" data-on-load=\"loadViewType\"");

WriteLiteral("data-page-name=\"");

            
            #line 37 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
                                                             Write(ViewBag.PageName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></div>\r\n");

            
            #line 38 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 39 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(User.Identity.IsAuthenticated ? Html.Action(MVC.User.UserHeader()) : Html.Partial(MVC.Shared.Views.SiteLayout._HeaderAnonymous));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 40 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(Html.Action(MVC.Home.MobileMenu()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 41 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(User.Identity.IsAuthenticated ? Html.Action(MVC.Home.SideMenuRight()) : Html.Partial(MVC.Shared.Views.SiteLayout._SideMenuRightAnonymous));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 42 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(Html.Action(MVC.Home.MainMenu()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"site-map\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"SiteMap\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
       Write(Html.MvcSiteMap().SiteMapPath());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"rendered-body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"section-wrap\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"section overflowable\"");

WriteLiteral(">\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2588), Tuple.Create("\"", 2694)
, Tuple.Create(Tuple.Create("", 2596), Tuple.Create("sidebar", 2596), true)
, Tuple.Create(Tuple.Create(" ", 2603), Tuple.Create("left", 2604), true)
, Tuple.Create(Tuple.Create(" ", 2608), Tuple.Create("user-profile-lay", 2609), true)
, Tuple.Create(Tuple.Create(" ", 2625), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 51 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
                                                           if (ViewBag.HasSearchbar == true) {
            
            #line default
            #line hidden
WriteLiteralTo(__razor_attribute_value_writer, "contains-searchbar");

            
            #line 51 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
                                                                                                                             }
            
            #line default
            #line hidden
}), 2626), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 52 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
               Write(Html.Action(MVC.Profile.Header()));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 53 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
               Write(Html.Action(MVC.Profile.Menu()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2852), Tuple.Create("\"", 2942)
, Tuple.Create(Tuple.Create("", 2860), Tuple.Create("content", 2860), true)
, Tuple.Create(Tuple.Create(" ", 2867), Tuple.Create("right", 2868), true)
, Tuple.Create(Tuple.Create(" ", 2873), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 55 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
                                           if (ViewBag.HasSearchbar == true) {
            
            #line default
            #line hidden
WriteLiteralTo(__razor_attribute_value_writer, "contains-searchbar");

            
            #line 55 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
                                                                                                             }
            
            #line default
            #line hidden
}), 2874), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 56 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral("></div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 62 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(Html.Partial(MVC.Shared.Views.SiteLayout._Footer));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" id=\"goUpBtn\"");

WriteLiteral(" class=\"tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3196), Tuple.Create("\"", 3215)
            
            #line 63 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3204), Tuple.Create<System.Object, System.Int32>(Admin.GoUp
            
            #line default
            #line hidden
, 3204), false)
);

WriteLiteral(">\r\n        <i");

WriteLiteral(" class=\"fa fa-arrow-up fa-2x go-up-icon\"");

WriteLiteral("></i>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"shadow-film closed\"");

WriteLiteral("></div>\r\n    <svg");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <symbol");

WriteLiteral(" id=\"svg-arrow\"");

WriteLiteral(" viewBox=\"0 0 3.923 6.64014\"");

WriteLiteral(" preserveAspectRatio=\"xMinYMin meet\"");

WriteLiteral(">\r\n            <path");

WriteLiteral(" d=\"M3.711,2.92L0.994,0.202c-0.215-0.213-0.562-0.213-0.776,0c-0.215,0.215-0.215,0" +
".562,0,0.777l2.329,2.329\r\n\t\t\tL0.217,5.638c-0.215,0.215-0.214,0.562,0,0.776c0.214" +
",0.214,0.562,0.215,0.776,0l2.717-2.718C3.925,3.482,3.925,3.135,3.711,2.92z\"");

WriteLiteral(" />\r\n        </symbol>\r\n    </svg>\r\n    <svg");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <symbol");

WriteLiteral(" id=\"svg-star\"");

WriteLiteral(" viewBox=\"0 0 10 10\"");

WriteLiteral(" preserveAspectRatio=\"xMinYMin meet\"");

WriteLiteral(">\r\n            <polygon");

WriteLiteral(" points=\"4.994,0.249 6.538,3.376 9.99,3.878 7.492,6.313 8.082,9.751 4.994,8.129 1" +
".907,9.751\r\n\t2.495,6.313 -0.002,3.878 3.45,3.376 \"");

WriteLiteral(" />\r\n        </symbol>\r\n    </svg>\r\n    <svg");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <symbol");

WriteLiteral(" id=\"svg-plus\"");

WriteLiteral(" viewBox=\"0 0 13 13\"");

WriteLiteral(" preserveAspectRatio=\"xMinYMin meet\"");

WriteLiteral(">\r\n            <rect");

WriteLiteral(" x=\"5\"");

WriteLiteral(" width=\"3\"");

WriteLiteral(" height=\"13\"");

WriteLiteral(" />\r\n            <rect");

WriteLiteral(" y=\"5\"");

WriteLiteral(" width=\"13\"");

WriteLiteral(" height=\"3\"");

WriteLiteral(" />\r\n        </symbol>\r\n    </svg>\r\n");

WriteLiteral("    ");

            
            #line 85 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(Scripts.Render("~/bundles/panelscripts/js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 86 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(RenderSection("scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 87 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(Html.Partial(MVC.Shared.Views._Noty));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 88 "..\..\Views\Shared\SiteLayout\Profile\_ProfileLayout.cshtml"
Write(Html.Partial(MVC.Shared.Views.SiteLayout._Script));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("> sideMenuNovinak(); </script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
