#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Shared.SiteLayout
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/SiteLayout/_SideMenuRightAnonymous.cshtml")]
    public partial class _SideMenuRightAnonymous : Advertise.Web.Framework.ViewEngines.Razor.WebViewPage<dynamic>
    {
        public _SideMenuRightAnonymous()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"account-options-menu\"");

WriteLiteral(" class=\"side-menu right closed\"");

WriteLiteral(">\r\n    <svg");

WriteLiteral(" class=\"svg-plus\"");

WriteLiteral(">\r\n        <use");

WriteLiteral(" xlink:href=\"#svg-plus\"");

WriteLiteral("></use>\r\n    </svg>\r\n    <div");

WriteLiteral(" class=\"side-menu-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"user-quickview\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"user-board-option\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 362), Tuple.Create("\"", 401)
            
            #line 10 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 369), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.Login())
            
            #line default
            #line hidden
, 369), false)
);

WriteLiteral(" class=\"outer-avatar-ring tooltipster\"");

WriteAttribute("title", Tuple.Create(" title=\"", 440), Tuple.Create("\"", 460)
            
            #line 10 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
                             , Tuple.Create(Tuple.Create("", 448), Tuple.Create<System.Object, System.Int32>(Admin.Login
            
            #line default
            #line hidden
, 448), false)
);

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"inner-avatar-ring\"");

WriteLiteral(">\r\n                            <figure");

WriteLiteral(" class=\"user-header-avatar\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"anonymous-avatar-top\"");

WriteLiteral(" alt=\"anonymous avatar image\"");

WriteLiteral("></div>\r\n                            </figure>\r\n                        </div>\r\n " +
"                   </a>\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"quick-name\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 872), Tuple.Create("\"", 965)
            
            #line 19 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 879), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.Login().AddRouteValues(new {returnUrl = Request.UrlReferrer}))
            
            #line default
            #line hidden
, 879), false)
);

WriteLiteral(">\r\n                        <p");

WriteLiteral(" class=\"header-quick-name\"");

WriteLiteral(">");

            
            #line 20 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
                                                Write(Admin.WelcomeToNovinak);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </a>\r\n                </li>\r\n            </ul>\r\n       " +
"     <ul");

WriteLiteral(" class=\"option-menu-widget widget-anonymous\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"widget-fa\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1243), Tuple.Create("\"", 1285)
            
            #line 26 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 1250), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Home.SetLang("fa"))
            
            #line default
            #line hidden
, 1250), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-language fa-2x widget-icon\"");

WriteLiteral("></i>\r\n                        <span>فارسی</span>\r\n                    </a>\r\n    " +
"            </li>\r\n                <li");

WriteLiteral(" class=\"widget-en\"");

WriteLiteral(">\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1518), Tuple.Create("\"", 1560)
            
            #line 32 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 1525), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Home.SetLang("en"))
            
            #line default
            #line hidden
, 1525), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-language fa-flip-horizontal fa-2x widget-icon\"");

WriteLiteral("></i>\r\n                        <span>English</span>\r\n                    </a>\r\n  " +
"              </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    <ul");

WriteLiteral(" class=\"dropdown dark hover-effect\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"dropdown-item interactive\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1906), Tuple.Create("\"", 1942)
            
            #line 42 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 1913), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Page.Costs())
            
            #line default
            #line hidden
, 1913), false)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sl-icon fa fa-briefcase fa-2x anonymous-option-icon\"");

WriteLiteral("></span>\r\n                <span>");

            
            #line 44 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
                 Write(Admin.BusinessRegistration);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"dropdown-item interactive\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2190), Tuple.Create("\"", 2229)
            
            #line 48 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 2197), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.Login())
            
            #line default
            #line hidden
, 2197), false)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sl-icon fa fa-shopping-cart fa-2x fa-flip-horizontal anonymous-option-ico" +
"n\"");

WriteLiteral("></span>\r\n                <span>");

            
            #line 50 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
                 Write(Admin.Cart);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"dropdown-item interactive\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2484), Tuple.Create("\"", 2577)
            
            #line 54 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 2491), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.Login().AddRouteValues(new {returnUrl = Request.UrlReferrer}))
            
            #line default
            #line hidden
, 2491), false)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sl-icon fa fa-sign-in fa-2x anonymous-option-icon\"");

WriteLiteral("></span>\r\n                <span>");

            
            #line 56 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
                 Write(Admin.Login);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </a>\r\n        </li>\r\n        <li");

WriteLiteral(" class=\"dropdown-item interactive\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2808), Tuple.Create("\"", 2855)
            
            #line 60 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
, Tuple.Create(Tuple.Create("", 2815), Tuple.Create<System.Object, System.Int32>(Url.Action(MVC.Account.EmailRegister())
            
            #line default
            #line hidden
, 2815), false)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sl-icon fa fa-user-plus fa-2x anonymous-option-icon\"");

WriteLiteral("></span>\r\n                <span>");

            
            #line 62 "..\..\Views\Shared\SiteLayout\_SideMenuRightAnonymous.cshtml"
                 Write(Admin.Register);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </a>\r\n        </li>\r\n    </ul>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
