#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advertise.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Advertise;
    using Advertise.Core.Languages;
    using Advertise.Web;
    using Advertise.Web.Framework.ViewEngines.Razor;
    using MvcSiteMapProvider.Web.Html;
    using MvcSiteMapProvider.Web.Html.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public class CheckBoxListBuilder : System.Web.WebPages.HelperPage
    {

#line 2 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
public static System.Web.WebPages.HelperResult CheckBoxList(string name, IEnumerable<SelectListItem> items)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 3 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    <div");

WriteLiteralTo(__razor_helper_writer, " class=\"row\"");

WriteLiteralTo(__razor_helper_writer, ">\n");


#line 5 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
        

#line default
#line hidden

#line 5 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
         foreach (var item in items)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            ");

WriteLiteralTo(__razor_helper_writer, "\n                <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-md-6\"");

WriteLiteralTo(__razor_helper_writer, ">\n                    <input");

WriteLiteralTo(__razor_helper_writer, " type=\"checkbox\"");

WriteLiteralTo(__razor_helper_writer, " ");


#line 9 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
                                            if (item.Selected) {

#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, " ");

WriteLiteralTo(__razor_helper_writer, " checked=\"checked\" ");

WriteLiteralTo(__razor_helper_writer, "  ");


#line 9 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
                                                                                                   }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "                           id=\"");


#line 10 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
 WriteTo(__razor_helper_writer, item.Value);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\" name=\"");


#line 10 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
                    WriteTo(__razor_helper_writer, name);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\" value=\"");


#line 10 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
                                  WriteTo(__razor_helper_writer, item.Value);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\" class=\"checkbox-inline\" />\n                    <label");

WriteAttributeTo(__razor_helper_writer, "for", Tuple.Create(" for=\"", 482), Tuple.Create("\"", 499)

#line 11 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
, Tuple.Create(Tuple.Create("", 488), Tuple.Create<System.Object, System.Int32>(item.Value

#line default
#line hidden
, 488), false)
);

WriteLiteralTo(__razor_helper_writer, " class=\"control-label\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 11 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
                                     WriteTo(__razor_helper_writer, item.Text);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</label>\n                </div>\n            ");

WriteLiteralTo(__razor_helper_writer, "\n");


#line 14 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    </div>\n");


#line 16 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"


#line default
#line hidden
});

#line 16 "..\..\Views\Shared\CheckBoxListBuilder.cshtml"
}
#line default
#line hidden

    }
}
#pragma warning restore 1591
